import fixtures from './__fixtures__/crags.json';
import {
  accessView,
  approachLabel,
  attributionLine,
  bandSegments,
  cragGradeRange,
  cragRowMeta,
  FQME_MAP_URL,
  inQuebec,
  licenceName,
  routesLabel,
  sectorList,
  styleLine,
  styleNames,
  summaryFromDetail,
  topoCredits,
} from './card';
import { parseCragTile } from './crag';
import { parseCragDetail } from './detail';

describe('access', () => {
  it('never reads missing data as open; Québec points to FQME', () => {
    const qc = accessView('unknown', { lat: 46.8, lng: -71.5 });
    expect(qc).toEqual({
      status: 'unknown',
      tone: 'unknown',
      label: 'Access unknown · check FQME',
      url: FQME_MAP_URL,
    });
    const vt = accessView('unknown', { lat: 44.3, lng: -72.9 });
    expect(vt.label).toBe('Access unknown · check locally before you go');
    expect(vt.url).toBeNull();
    // The topo's country/province, when known, beats the box.
    expect(
      accessView('unknown', { lat: 46.8, lng: -71.5, cc: 'CA', admin1: 'Ontario' }).url,
    ).toBeNull();
    expect(accessView('unknown', { lat: 0, lng: 0, cc: 'CA', admin1: 'Québec' }).url).toBe(
      FQME_MAP_URL,
    );
  });

  it('labels restrictions and partner statuses', () => {
    const where = { lat: 46.8, lng: -71.5 };
    expect(accessView('closed', where).tone).toBe('danger');
    expect(accessView('banned', where).label).toBe('Climbing banned');
    expect(accessView('restricted', where, { src: 'fqme', note: 'Nesting season' }).label).toBe(
      'Access restricted · FQME · Nesting season',
    );
    expect(accessView('open', where, { src: 'fqme', url: 'https://fqme.example/x' })).toEqual({
      status: 'open',
      tone: 'ok',
      label: 'Access open · FQME',
      url: 'https://fqme.example/x',
    });
  });

  it('knows roughly where Québec is', () => {
    expect(inQuebec(45.95, -74.53)).toBe(true); // Weir
    expect(inQuebec(47.9, -69.97)).toBe(true); // Palissades
    expect(inQuebec(44.3, -72.9)).toBe(false); // Vermont
    expect(inQuebec(46.0, -66.6)).toBe(false); // New Brunswick
    expect(inQuebec(53.5, -60.0)).toBe(false); // Labrador
  });
});

describe('card lines', () => {
  const weir = parseCragTile(fixtures['Weir tile'] as never)!;

  it('bars and legends the bands', () => {
    const segs = bandSegments([4, 20, 7, 6], 'yds');
    expect(segs.map((s) => [s.label, s.count])).toEqual([
      ['≤ 5.7', 4],
      ['5.8–5.10', 20],
      ['5.11', 7],
      ['5.12+', 6],
    ]);
    expect(segs.reduce((a, s) => a + s.share, 0)).toBeCloseTo(1);
    expect(bandSegments([0, 0, 0, 0], 'yds')).toEqual([]);
    expect(bandSegments([0, 3, 0, 0], 'french').map((s) => s.label)).toEqual(['5b–6b+']);
  });

  it('writes the row, range and style lines', () => {
    expect(cragGradeRange(weir.ranges, weir.styles, 'yds')).toBe('5.2 – 5.15b');
    expect(cragRowMeta(weir, 'yds', '10 km away')).toBe('230 routes · 5.2 – 5.15b · 10 km away');
    expect(cragRowMeta({ routes: 0, ranges: {}, styles: [] }, 'yds', null)).toBe(
      'No route list yet',
    );
    expect(styleLine({ sport: 18, trad: 19, tr: 2, ice: 1 })).toBe(
      '19 trad · 18 sport · 2 top rope',
    );
    expect(styleNames(['sport', 'boulder'])).toBe('Sport · Boulder');
    expect(routesLabel(1)).toBe('1 route');
    expect(routesLabel(2721)).toBe('2,721 routes');
    expect(approachLabel(15)).toBe('15 min approach');
    expect(approachLabel(90)).toBe('1 h 30 approach');
    expect(approachLabel(120)).toBe('2 h approach');
    expect(approachLabel(null)).toBeNull();
    expect(sectorList(['A', 'B', 'C', 'D', 'E'])).toBe('A · B · C · +2 more');
  });

  it('credits the sources as the mockups do', () => {
    expect(attributionLine(['ob'])).toBe('Route data: OpenBeta (CC0)');
    expect(attributionLine(['ob', 'osm'])).toBe(
      'Crag: OpenBeta (CC0) · routes © OpenStreetMap contributors (ODbL)',
    );
    expect(attributionLine(['osm', 'c2c'])).toBe(
      'Route data © OpenStreetMap contributors (ODbL) · camptocamp.org (CC BY-SA)',
    );
    expect(attributionLine(['c2c'])).toBe('Crag: camptocamp.org (CC BY-SA)');
    const d = parseCragDetail(fixtures.Weir)!;
    expect(topoCredits(d.sources, true)).toEqual([
      'Routes: OpenBeta (CC0)',
      'Routes: © OpenStreetMap contributors (ODbL)',
      'Diagram generated by Inukshuk from the route starts, not to scale',
    ]);
    expect(licenceName('CC-BY-SA-3.0')).toBe('CC BY-SA 3.0');
    expect(licenceName('X')).toBe('X');
  });

  it('summarizes a saved topo like a tile', () => {
    const d = parseCragDetail(fixtures.Weir)!;
    const s = summaryFromDetail(d);
    expect(s).toMatchObject({ uid: d.uid, routes: 230, diagram: true, region: 'Laurentides' });
    expect(s.version).toBe(d.v);
  });
});
