// @ts-check
const {
  withAppDelegate,
  withDangerousMod,
  withInfoPlist,
  withXcodeProject,
  IOSConfig,
} = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Adopt the UIKit scene lifecycle on iOS.
 *
 * Apps linked against the iOS 27 SDK must use scenes: a Release build made
 * with Xcode 27 dies at launch with EXC_BREAKPOINT in
 * `___UIApplicationEvaluateRuntimeIssueForNoSceneLifecycleAdoption_block_invoke`
 * (from `-[UIApplication workspace:didCreateScene:withTransitionContext:completion:]`)
 * when Info.plist declares no UIApplicationSceneManifest.
 *
 * Expo SDK 56's template has no scene support. Upstream added it in SDK 57.0.23
 * (`ExpoAppSceneDelegate` + expo-build-properties `ios.enableSceneSupport`) and
 * makes it the default template in SDK 58; this plugin is the SDK 56 port of
 * the same design and should be deleted on the SDK 57/58 upgrade.
 *
 * What it does at prebuild:
 * 1. Info.plist: a single-scene UIApplicationSceneManifest whose delegate is
 *    `InukshukSceneDelegate`.
 * 2. AppDelegate.swift: stops creating the window and starting React Native
 *    in didFinishLaunching (the scene delegate does it), except on a
 *    background relaunch for location or for CoreBluetooth state restoration
 *    (no scene connects then; the recording task and the GNSS link's JS sink
 *    must still run). Restoration itself is untouched: UIKit still calls the
 *    app delegate's didFinishLaunching with the launch options, and super
 *    forwards them to every ExpoAppDelegateSubscriber (InukshukGnss's).
 * 3. SceneDelegate.swift: creates the window from the UIWindowScene, starts
 *    React Native, and forwards scene events (URLs, user activities,
 *    foreground/background, quick actions) to the ExpoAppDelegate, whose
 *    overrides reach RCTLinkingManager and every ExpoAppDelegateSubscriber
 *    exactly as the app-delegate callbacks did before.
 */

const SCENE_DELEGATE_CLASS = 'InukshukSceneDelegate';
const SCENE_DELEGATE_FILE = 'SceneDelegate.swift';

const SCENE_MANIFEST = {
  UIApplicationSupportsMultipleScenes: false,
  UISceneConfigurations: {
    UIWindowSceneSessionRoleApplication: [
      {
        UISceneConfigurationName: 'Default Configuration',
        UISceneDelegateClassName: SCENE_DELEGATE_CLASS,
      },
    ],
  },
};

/** The SDK 56 template's startup block in didFinishLaunching. */
const LEGACY_STARTUP =
  /^[ \t]*#if os\(iOS\) \|\| os\(tvOS\)\r?\n[ \t]*window = UIWindow\(frame: UIScreen\.main\.bounds\)\r?\n[ \t]*factory\.startReactNative\(\r?\n[ \t]*withModuleName: "main",\r?\n[ \t]*in: window,\r?\n[ \t]*launchOptions: launchOptions\)\r?\n[ \t]*#endif\r?\n/m;

const SCENE_MARKER = '// @inukshuk/scene-lifecycle';

const SCENE_STARTUP = `    ${SCENE_MARKER}: the scene delegate (SceneDelegate.swift) creates the
    // window and starts React Native. A background relaunch connects no scene,
    // so for the two this app opts into, start React Native here as before:
    // - .location: TaskManager's recording task must run;
    // - .bluetoothCentrals: CoreBluetooth state restoration of the GNSS link
    //   (InukshukGnssAppDelegateSubscriber restores the central natively in
    //   super's didFinishLaunching; its buffered bytes reach JS once a sink
    //   attaches, which needs React Native running).
    // The scene delegate adopts this window if a scene connects later.
    let backgroundRelaunchKeys: [UIApplication.LaunchOptionsKey] = [.location, .bluetoothCentrals]
    if backgroundRelaunchKeys.contains(where: { launchOptions?[$0] != nil }) {
      window = UIWindow(frame: UIScreen.main.bounds)
      factory.startReactNative(
        withModuleName: "main",
        in: window,
        launchOptions: launchOptions)
    }
`;

const SCENE_DELEGATE_SOURCE = `internal import Expo
import React
import UIKit

// Generated by plugins/withIosSceneLifecycle.js — do not edit by hand.
//
// iOS 27 requires the scene lifecycle (apps linked against its SDK crash at
// launch in ___UIApplicationEvaluateRuntimeIssueForNoSceneLifecycleAdoption).
// Under scenes UIKit stops calling the app delegate's URL, user-activity and
// life-cycle methods, so this forwards each scene event to the AppDelegate:
// its overrides reach RCTLinkingManager and every ExpoAppDelegateSubscriber.
// Port of Expo SDK 57's ExpoAppSceneDelegate.
@objc(${SCENE_DELEGATE_CLASS})
final class SceneDelegate: UIResponder, UIWindowSceneDelegate {
  var window: UIWindow?

  private var appDelegate: AppDelegate? {
    UIApplication.shared.delegate as? AppDelegate
  }

  func scene(
    _ scene: UIScene,
    willConnectTo session: UISceneSession,
    options connectionOptions: UIScene.ConnectionOptions
  ) {
    guard let windowScene = scene as? UIWindowScene, let appDelegate = self.appDelegate else {
      return
    }

    if let existing = appDelegate.window, existing.rootViewController != nil {
      // React Native already started without a scene (background location relaunch).
      existing.windowScene = windowScene
      existing.makeKeyAndVisible()
      window = existing
    } else {
      guard let factory = appDelegate.reactNativeFactory else {
        fatalError("SceneDelegate: AppDelegate created no React Native factory.")
      }
      let window = UIWindow(windowScene: windowScene)
      self.window = window
      // Code that reads UIApplication.shared.delegate?.window (expo-system-ui,
      // expo-updates) keeps working.
      appDelegate.window = window
      // Cold-start URLs come in connectionOptions instead of the launch options
      // that Linking.getInitialURL() reads, so rebuild them.
      factory.startReactNative(
        withModuleName: "main",
        in: window,
        launchOptions: Self.launchOptions(
          url: connectionOptions.urlContexts.first?.url,
          userActivity: connectionOptions.userActivities.first {
            $0.activityType == NSUserActivityTypeBrowsingWeb
          }
        )
      )
    }

    // Subscribers (expo-linking's initial URL) still need to see a cold-start link.
    connectionOptions.urlContexts.forEach(forwardOpenURL)
    connectionOptions.userActivities.forEach(forwardContinue)
    if let shortcutItem = connectionOptions.shortcutItem {
      appDelegate.application(UIApplication.shared, performActionFor: shortcutItem) { _ in }
    }
  }

  func sceneDidDisconnect(_ scene: UIScene) {
    window = nil
  }

  func sceneDidBecomeActive(_ scene: UIScene) {
    appDelegate?.applicationDidBecomeActive(UIApplication.shared)
  }

  func sceneWillResignActive(_ scene: UIScene) {
    appDelegate?.applicationWillResignActive(UIApplication.shared)
  }

  func sceneWillEnterForeground(_ scene: UIScene) {
    appDelegate?.applicationWillEnterForeground(UIApplication.shared)
  }

  func sceneDidEnterBackground(_ scene: UIScene) {
    appDelegate?.applicationDidEnterBackground(UIApplication.shared)
  }

  func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
    URLContexts.forEach(forwardOpenURL)
  }

  func scene(_ scene: UIScene, willContinueUserActivityWithType userActivityType: String) {
    _ = appDelegate?.application(
      UIApplication.shared, willContinueUserActivityWithType: userActivityType)
  }

  func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
    forwardContinue(userActivity)
  }

  func scene(
    _ scene: UIScene,
    didFailToContinueUserActivityWithType userActivityType: String,
    error: Error
  ) {
    appDelegate?.application(
      UIApplication.shared, didFailToContinueUserActivityWithType: userActivityType, error: error)
  }

  func scene(_ scene: UIScene, didUpdate userActivity: NSUserActivity) {
    appDelegate?.application(UIApplication.shared, didUpdate: userActivity)
  }

  func windowScene(
    _ windowScene: UIWindowScene,
    performActionFor shortcutItem: UIApplicationShortcutItem,
    completionHandler: @escaping (Bool) -> Void
  ) {
    guard let appDelegate = self.appDelegate else {
      completionHandler(false)
      return
    }
    appDelegate.application(
      UIApplication.shared, performActionFor: shortcutItem, completionHandler: completionHandler)
  }

  // MARK: - Forwarding

  private func forwardOpenURL(_ context: UIOpenURLContext) {
    var options: [UIApplication.OpenURLOptionsKey: Any] = [:]
    if let sourceApplication = context.options.sourceApplication {
      options[.sourceApplication] = sourceApplication
    }
    if let annotation = context.options.annotation {
      options[.annotation] = annotation
    }
    options[.openInPlace] = context.options.openInPlace
    _ = appDelegate?.application(UIApplication.shared, open: context.url, options: options)
  }

  private func forwardContinue(_ userActivity: NSUserActivity) {
    _ = appDelegate?.application(
      UIApplication.shared, continue: userActivity, restorationHandler: { _ in })
  }

  /// The launch options React Native's getInitialURL() reads, or nil. Keys are
  /// spelled out because the UIApplication accessors are deprecated in iOS 26.
  private static func launchOptions(
    url: URL?,
    userActivity: NSUserActivity?
  ) -> [UIApplication.LaunchOptionsKey: Any]? {
    var launchOptions: [UIApplication.LaunchOptionsKey: Any] = [:]
    if let url {
      launchOptions[UIApplication.LaunchOptionsKey(rawValue: "UIApplicationLaunchOptionsURLKey")] =
        url
    }
    if let userActivity {
      launchOptions[
        UIApplication.LaunchOptionsKey(
          rawValue: "UIApplicationLaunchOptionsUserActivityDictionaryKey")] = [
        "UIApplicationLaunchOptionsUserActivityTypeKey": userActivity.activityType,
        "UIApplicationLaunchOptionsUserActivityKey": userActivity,
      ]
    }
    return launchOptions.isEmpty ? nil : launchOptions
  }
}
`;

/**
 * @param {Record<string, unknown>} infoPlist
 * @returns {Record<string, unknown>}
 */
function addSceneManifest(infoPlist) {
  const existing = infoPlist.UIApplicationSceneManifest;
  if (existing !== undefined && JSON.stringify(existing) !== JSON.stringify(SCENE_MANIFEST)) {
    throw new Error(
      'withIosSceneLifecycle: Info.plist already declares a different UIApplicationSceneManifest.',
    );
  }
  return { ...infoPlist, UIApplicationSceneManifest: SCENE_MANIFEST };
}

/**
 * @param {string} contents AppDelegate.swift from the SDK 56 template.
 * @returns {string}
 */
function updateAppDelegate(contents) {
  if (contents.includes(SCENE_MARKER)) {
    return contents;
  }
  if (!LEGACY_STARTUP.test(contents)) {
    throw new Error(
      'withIosSceneLifecycle: AppDelegate.swift is not the Expo SDK 56 template ' +
        '(window + startReactNative block not found). Re-check scene support for this SDK.',
    );
  }
  return contents.replace(LEGACY_STARTUP, SCENE_STARTUP);
}

/** @type {import('@expo/config-plugins').ConfigPlugin} */
function withIosSceneLifecycle(config) {
  config = withInfoPlist(config, (cfg) => {
    cfg.modResults = /** @type {any} */ (addSceneManifest(cfg.modResults));
    return cfg;
  });

  config = withAppDelegate(config, (cfg) => {
    if (cfg.modResults.language !== 'swift') {
      throw new Error('withIosSceneLifecycle: expected a Swift AppDelegate.');
    }
    cfg.modResults.contents = updateAppDelegate(cfg.modResults.contents);
    return cfg;
  });

  config = withDangerousMod(config, [
    'ios',
    async (cfg) => {
      const sourceRoot = IOSConfig.Paths.getSourceRoot(cfg.modRequest.projectRoot);
      fs.writeFileSync(path.join(sourceRoot, SCENE_DELEGATE_FILE), SCENE_DELEGATE_SOURCE);
      return cfg;
    },
  ]);

  config = withXcodeProject(config, (cfg) => {
    const projectName = cfg.modRequest.projectName;
    if (!projectName) {
      throw new Error('withIosSceneLifecycle: unknown iOS project name.');
    }
    const filepath = `${projectName}/${SCENE_DELEGATE_FILE}`;
    if (!cfg.modResults.hasFile(filepath)) {
      IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
        filepath,
        groupName: projectName,
        project: cfg.modResults,
      });
    }
    return cfg;
  });

  return config;
}

module.exports = withIosSceneLifecycle;
module.exports.addSceneManifest = addSceneManifest;
module.exports.updateAppDelegate = updateAppDelegate;
module.exports.SCENE_MANIFEST = SCENE_MANIFEST;
module.exports.SCENE_DELEGATE_SOURCE = SCENE_DELEGATE_SOURCE;
