/**
 * A real 32x24 PROGRESSIVE JPEG with restart markers every block, made with
 * libjpeg's `cjpeg -quality 90 -progressive -restart 1B` (#587): 10 scans with
 * DHT segments between them, 62 RST markers and stuffed 0xFF00 bytes inside
 * the entropy-coded data. jpeg-js can only write baseline files, so the
 * stripper's progressive tests use this one.
 */
export const PROGRESSIVE_JPEG_BASE64 =
  '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQ' +
  'ERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQU' +
  'FBQUFBQUFBQUFBQUFBT/wgARCAAYACADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAUGB//EABYBAQEBAAAAAAAA' +
  'AAAAAAAAAAYBA//dAAQAAf/aAAwDAQACEAMQAAABxN5WN0c//9CBZ3SXd5//0aJuBAf/AP/S1jPgNlP/xAAdEAACAgIDAQAA' +
  'AAAAAAAAAAADBAARAQUCFCES/9oACAEBAAEFAhoXP//QDr/P/9EKFZ//0jA6q/8A/9MaM//UAhU//9UKM//W3YK4/wD/1xo+' +
  'f//QHrvmf//RChmf/9JlfsN//8QAIhEAAQMEAAcAAAAAAAAAAAAAAQADIQIEBREGFDFBcZGx/9oACAEDAQE/Acbd9JX/0Hsz' +
  'yFjW+DIEeTAX/9HGO1Qv/9LiW6cFFuz2JJ9a19K//8QAJBEAAAUCBQUAAAAAAAAAAAAAAAECAxFBYQQFMXHwEiFRgaL/2gAI' +
  'AQIBAT8BezUkLmKc31t7H//QbxhG4SZ3t55eo//Rxrq+lSzoP//SZdWho3pk+31rcf/EACIQAAIBAgUFAAAAAAAAAAAAAAAB' +
  'EQIDEiExQVFhgaHB8P/aAAgBAQAGPwLg/9BZeD//0dD/0q7mUpTDP//TR//UTS3P/9X2f//WtWY3xOn7uf/X0P/QP//R6H//' +
  '0rtcJKp5Rwf/xAAgEAACAgICAgMAAAAAAAAAAAABEQAhMUFR8HGBkbHB/9oACAEBAAE/IQgGCFa7qf/QQ3JBdOf/0SgO1WHi' +
  'f//SCXSuTZ0F57x//9M6RLHoT//UKAfkAcz/1VFHdj9T/9ZVAySgeEI//9fCvbBGJ//Q1AOUj9T/0aJwlaAM/9IQXCMUtA/E' +
  '/9oADAMBAAIAAwAAABAr/9Cb/9GP/9Lz/8QAHBEBAAMAAgMAAAAAAAAAAAAAAQARITFRcZGh/9oACAEDAQE/ELyH/9CuzJrn' +
  '2FLadDpzP//Rui5//9Iqu68kfEv/xAAcEQEBAQACAwEAAAAAAAAAAAABESExQQBhgaH/2gAIAQIBAT8QYaXSVzNAUzo01eGf' +
  '/9AYuL0XDVjK/pE35//Rqioz0VJkeM2s78//0q3h23ty4eon2E//xAAfEAEBAAIDAQADAQAAAAAAAAABESExAEFRYXGBwdH/' +
  '2gAIAQEAAT8QneclkX8OF/ruc//QPC0MMkJgILf65//RFA/Yq8xH5NfXP//SA5GHskbpVq+uN8f/03NOsvyYtcY6+vx//9Sm' +
  'EQpUPduMAZ2/ef/VrmU9g0Sl81dIezn/1j6hxhWfQK4ykNd//9dgDGSAtLnuNO+7dc//0ERApoBBsQavzzPv/9FqgyIyBaAl' +
  'kP8Ae+f/0gO+HcDB3YrrPmOf/9k=';
