import { CONVERT_CREDITS } from '@core/convert/credits';
import { MARINE_ENABLED, VECTOR_BASEMAP_ENABLED, WEATHER_ENABLED } from '@core/features/flags';
import { MARINE_DISCLAIMER, OPENSEAMAP_ATTRIBUTION } from '@core/geo/marineLayers';
import { MARINE_SOURCES, NOAA_ENC_ATTRIBUTION } from '@core/geo/marineSources';
import { ECCC_ATTRIBUTION } from '@core/geo/weatherLayers';
import { CHS_TIDES_ATTRIBUTION } from '@core/weather/tides';

/**
 * The one place data credits live (the map hides MapLibre's own attribution
 * button — owner call, it crowded the map), assembled from the real
 * attribution constants rather than a hand-copied literal so a new source
 * can never ship uncredited.
 *
 * That matters most for bathymetry: the worldwide coverage ladder (wave D
 * §D3) draws from four providers depending on where the boat is, and GEBCO's
 * citation line is a LICENCE REQUIREMENT, not a courtesy. Each source's own
 * "Not for navigation." sentence is folded into the single closing notice so
 * the roll stays readable while the condition stays stated.
 */

/** Strip a source's trailing non-navigational sentence (stated once below). */
function withoutDisclaimer(line: string): string {
  return line.replace(new RegExp(`\\s*${MARINE_DISCLAIMER}\\.?$`, 'i'), '');
}

/**
 * Credits follow the FEATURES, not the codebase (see `@core/features/flags`).
 * Attribution is owed for data the app actually fetches and shows; a parked
 * feature fetches nothing, so crediting ECCC or CHS while weather and marine
 * are greyed out would list sources this build never contacts — and would
 * leave the reader hunting a map layer that isn't there. The lines come back
 * with the features, from the same attribution constants as before, so no
 * source can ship uncredited once it is live again.
 */
const PARTS: readonly string[] = [
  '© OpenStreetMap contributors',
  ...(VECTOR_BASEMAP_ENABLED
    ? [
        'Vector map: Protomaps',
        'Province & state names: Natural Earth (public domain)',
        'Map font: Atkinson Hyperlegible Next',
      ]
    : []),
  // The map's ⓘ credits sheet names the imagery providers (`mapCredits`);
  // the full roll must name every one of them too.
  'Satellite imagery: Esri, Maxar, Earthstar Geographics',
  'AWS Terrain Tiles',
  'MapLibre',
  ...(WEATHER_ENABLED
    ? [`Weather: ${ECCC_ATTRIBUTION}`, 'Weather-mode labels: OpenFreeMap (© OpenMapTiles)']
    : []),
  ...(MARINE_ENABLED
    ? [
        ...MARINE_SOURCES.map((s) => withoutDisclaimer(s.attribution)),
        withoutDisclaimer(NOAA_ENC_ATTRIBUTION),
        OPENSEAMAP_ATTRIBUTION,
      ]
    : []),
  // The geodetic-points extension: each agency's credit and licence are
  // listed in full under Coverage & sources, and on every mark's card.
  'Geodetic points: national and provincial survey agencies (see Settings › Extensions › Coverage & sources) and OpenStreetMap contributors',
  // Overlays → Tide stations (infra/tiles/nas/tides.sh). CHS is not in it.
  'Tide stations: NOAA/NOS/CO-OPS (public domain) · Shom, 2025. Références Altimétriques Maritimes, doi:10.17183/MAREE_COURANTS_RAM (Licence Ouverte 2.0) · © Kartverket (CC BY 4.0) · 出典：気象庁 (Japan Meteorological Agency, Public Data Licence 1.0) · Canada: contains data of the Canadian Hydrographic Service (DFO), fetched live by this device from CHS IWLS, under the CHS Licence Agreement · not for navigation',
  // Convert (PROJ, the EPSG Dataset's terms, every grid agency's licence).
  CONVERT_CREDITS,
  // The climbing-crags extension (infra/tiles/nas/climbing.sh): facts only,
  // each crag's sources on its card and topo.
  'Climbing crags: OpenBeta (CC0) · route starts and walls © OpenStreetMap contributors (ODbL) · approach notes camptocamp.org contributors (CC BY-SA 3.0) · wall diagrams generated by Inukshuk',
  // Tides ride the forecast card, which is gated on weather OR marine.
  ...(WEATHER_ENABLED || MARINE_ENABLED ? [`Tides: ${CHS_TIDES_ATTRIBUTION}`] : []),
];

/** The closing non-navigational notice only applies when depth data ships. */
const DEPTH_NOTICE = MARINE_ENABLED
  ? ` · All depth data is for reference only — ${MARINE_DISCLAIMER.toLowerCase()}.`
  : '';

export const MAP_DATA_CREDITS = `${PARTS.join(' · ')}${DEPTH_NOTICE}`;
