// C++ engine tests: parity with the TS reference (fixtures/parity.json,
// generated by src/core/terrain3d/parity.test.ts), the PNG decoder, and the
// stateful engine (caches, morphs, fallbacks, memory). Run: tests/run.sh
#include <zlib.h>

#include <cmath>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <map>
#include <set>
#include <memory>
#include <random>
#include <sstream>
#include <string>
#include <variant>
#include <vector>

#include "../cpp/png_decode.hpp"
#include "../cpp/terrain_core.hpp"
#include "../cpp/terrain_engine.hpp"

using namespace inukshuk::terrain;

// ---- tiny test harness ---------------------------------------------------------
static int g_checks = 0, g_failures = 0, g_cases = 0;
#define CHECK(cond)                                                          \
  do {                                                                       \
    g_checks++;                                                              \
    if (!(cond)) {                                                           \
      g_failures++;                                                          \
      std::fprintf(stderr, "FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond);   \
    }                                                                        \
  } while (0)
#define CHECK_NEAR(a, b, eps)                                                          \
  do {                                                                                 \
    g_checks++;                                                                        \
    const double _a = (a), _b = (b);                                                   \
    if (!(std::abs(_a - _b) <= (eps))) {                                               \
      g_failures++;                                                                    \
      std::fprintf(stderr, "FAIL %s:%d: %s=%.17g vs %s=%.17g\n", __FILE__, __LINE__, #a, \
                   _a, #b, _b);                                                        \
    }                                                                                  \
  } while (0)

// ---- minimal JSON ----------------------------------------------------------------
struct Json;
using JsonArr = std::vector<Json>;
using JsonObj = std::map<std::string, Json>;
struct Json {
  std::variant<std::nullptr_t, bool, double, std::string, std::shared_ptr<JsonArr>,
               std::shared_ptr<JsonObj>>
      v;
  double num() const { return std::get<double>(v); }
  bool boolean() const { return std::get<bool>(v); }
  const std::string& str() const { return std::get<std::string>(v); }
  const JsonArr& arr() const { return *std::get<std::shared_ptr<JsonArr>>(v); }
  const Json& operator[](const std::string& k) const {
    return std::get<std::shared_ptr<JsonObj>>(v)->at(k);
  }
  const Json& operator[](size_t i) const { return arr().at(i); }
};
struct Parser {
  const std::string& s;
  size_t i = 0;
  void ws() {
    while (i < s.size() && std::isspace(static_cast<unsigned char>(s[i]))) i++;
  }
  Json parse() {
    ws();
    const char c = s[i];
    if (c == '{') {
      i++;
      auto o = std::make_shared<JsonObj>();
      ws();
      if (s[i] == '}') {
        i++;
        return {o};
      }
      while (true) {
        ws();
        std::string k = parse().str();
        ws();
        i++;  // :
        (*o)[k] = parse();
        ws();
        if (s[i] == ',') {
          i++;
          continue;
        }
        i++;  // }
        return {o};
      }
    }
    if (c == '[') {
      i++;
      auto a = std::make_shared<JsonArr>();
      ws();
      if (s[i] == ']') {
        i++;
        return {a};
      }
      while (true) {
        a->push_back(parse());
        ws();
        if (s[i] == ',') {
          i++;
          continue;
        }
        i++;  // ]
        return {a};
      }
    }
    if (c == '"') {
      i++;
      std::string out;
      while (s[i] != '"') {
        if (s[i] == '\\') i++;
        out += s[i++];
      }
      i++;
      return {out};
    }
    if (s.compare(i, 4, "null") == 0) {
      i += 4;
      return {nullptr};
    }
    if (s.compare(i, 4, "true") == 0) {
      i += 4;
      return {true};
    }
    if (s.compare(i, 5, "false") == 0) {
      i += 5;
      return {false};
    }
    size_t end = i;
    while (end < s.size() && (std::isdigit(static_cast<unsigned char>(s[end])) || s[end] == '-' ||
                              s[end] == '+' || s[end] == '.' || s[end] == 'e' || s[end] == 'E'))
      end++;
    const double d = std::strtod(s.c_str() + i, nullptr);
    i = end;
    return {d};
  }
};

// ---- parity -----------------------------------------------------------------------
static void testParity(const Json& fx) {
  // Cameras: eye + selections (flat, and with heights).
  for (const auto& c : fx["cameras"].arr()) {
    g_cases++;
    FrameCamera cam;
    for (int k = 0; k < 16; k++) cam.P[k] = c["P"][k].num();
    cam.width = c["width"].num();
    cam.height = c["height"].num();
    cam.fovRad = c["fov"].num();
    cam.zoom = c["zoom"].num();
    cam.lat = c["lat"].num();
    auto eye = eyeFromProjection(cam.P);
    CHECK(eye.has_value());
    for (int k = 0; k < 3; k++) CHECK_NEAR((*eye)[k], c["eye"][k].num(), 1e-6 * std::max(1.0, std::abs(c["eye"][k].num())));

    LodOptions flat;
    flat.heightScale = 0;
    const Selection s1 = selectTiles(cam, flat);
    const auto& want1 = c["flat"]["tiles"].arr();
    CHECK(s1.tiles.size() == want1.size());
    for (size_t k = 0; k < std::min(s1.tiles.size(), want1.size()); k++)
      CHECK(tileKey(s1.tiles[k].tile) == want1[k].str());
    CHECK_NEAR(s1.threshold, c["flat"]["threshold"].num(), 1e-9);

    LodOptions tall;
    tall.heightRange = [](const TileId& t) -> std::optional<std::pair<double, double>> {
      if (t.z >= 8) return std::make_pair(800.0 + t.z * 10, 3200.0 + t.z * 20);
      return std::nullopt;
    };
    tall.hRef = 1200;
    tall.heightScale = 1.3;
    const Selection s2 = selectTiles(cam, tall);
    const auto& want2 = c["tall"]["tiles"].arr();
    CHECK(s2.tiles.size() == want2.size());
    for (size_t k = 0; k < std::min(s2.tiles.size(), want2.size()); k++)
      CHECK(tileKey(s2.tiles[k].tile) == want2[k].str());
  }
  // Terrarium decode.
  for (const auto& d : fx["decode"].arr()) {
    g_cases++;
    const int r = static_cast<int>(d[0].num()), g = static_cast<int>(d[1].num()),
              b = static_cast<int>(d[2].num());
    CHECK_NEAR(terrariumHeight(r, g, b), d[3].num(), 1e-9);
    CHECK_NEAR(terrariumHeight(r, g, b, false), d[4].num(), 1e-9);
  }
  // Mesh.
  {
    g_cases++;
    const auto& m = fx["mesh"];
    const int n = static_cast<int>(m["n"].num());
    auto verts = buildGridVertices(n);
    auto idx = buildGridIndices(n);
    CHECK(verts.size() == m["vertices"].arr().size());
    for (size_t k = 0; k < verts.size(); k++) CHECK_NEAR(verts[k], m["vertices"][k].num(), 1e-7);
    CHECK(idx.size() == m["indices"].arr().size());
    for (size_t k = 0; k < idx.size(); k++) CHECK(idx[k] == static_cast<uint32_t>(m["indices"][k].num()));
    std::vector<float> parent;
    for (const auto& p : m["parent"].arr()) parent.push_back(static_cast<float>(p.num()));
    auto c10 = parentSurfaceForChild(n, parent, 1, 0);
    auto c11 = parentSurfaceForChild(n, parent, 1, 1);
    for (size_t k = 0; k < c10.size(); k++) CHECK_NEAR(c10[k], m["child10"][k].num(), 1e-3);
    for (size_t k = 0; k < c11.size(); k++) CHECK_NEAR(c11[k], m["child11"][k].num(), 1e-3);
    auto slopes = bakeSlopes(n, [](double u, double v) { return 1000 + 300 * u - 700 * v; }, 125);
    for (size_t k = 0; k < slopes.size(); k++) CHECK_NEAR(slopes[k], m["planeSlopes"][k].num(), 1e-4);
  }
  // Mosaic sampling.
  {
    auto mtile = [](int tx, int ty) {
      std::vector<float> t(64);
      for (int k = 0; k < 64; k++)
        t[k] = static_cast<float>((tx * 8 + (k % 8)) * 3 + (ty * 8 + k / 8) * 7 + ((k * 13) % 5));
      return t;
    };
    std::map<int, std::vector<float>> tiles;
    for (int dy = -1; dy <= 1; dy++)
      for (int dx = -1; dx <= 1; dx++) tiles[(dy + 1) * 3 + (dx + 1)] = mtile(dx, dy);
    DemNeighborhood nb;
    nb.size = 8;
    for (int i = 0; i < 9; i++) nb.around[i] = tiles[i].data();
    nb.around[8] = nullptr;  // (1, 1) missing
    nb.center = nb.around[4];
    for (const auto& s : fx["mosaic"].arr()) {
      g_cases++;
      CHECK_NEAR(sampleMosaic(nb, s[0].num(), s[1].num()), s[2].num(), 1e-6);
    }
  }
  // Scalars.
  const auto& sc = fx["scalar"];
  for (const auto& p : sc["smoothstep"].arr()) CHECK_NEAR(smoothstep(0, 1, p[0].num()), p[1].num(), 1e-12);
  for (const auto& p : sc["pitchRamp"].arr()) CHECK_NEAR(pitchRamp(p[0].num()), p[1].num(), 1e-12);
  for (const auto& p : sc["morph"].arr()) CHECK_NEAR(morphFactor(p[0].num()), p[1].num(), 1e-12);
  for (const auto& p : sc["fog"].arr())
    CHECK_NEAR(fogAmount(2.5, 0.12, 12, p[0].num()), p[1].num(), 1e-12);
  for (const auto& p : sc["light"].arr()) {
    auto l = lightDirection(p[0].num());
    for (int k = 0; k < 3; k++) CHECK_NEAR(l[k], p[k + 1].num(), 1e-12);
  }
  for (const auto& p : sc["form"].arr())
    CHECK_NEAR(formShade(p[0].num(), p[1].num(), 1.6, lightDirection(30), 0.22, 0.8), p[2].num(), 1e-12);
  g_cases += 6;
  // DEM request plan.
  {
    g_cases++;
    std::vector<TileId> tiles;
    for (const auto& k : fx["plan"]["tiles"].arr()) {
      TileId t;
      std::sscanf(k.str().c_str(), "%d/%d/%d/%d", &t.z, &t.x, &t.y, &t.wrap);
      tiles.push_back(t);
    }
    auto plan = planDemRequests(
        tiles, 30,
        [](const DemId& d) { return demKey(d) == "10/533/361" || demKey(d) == "13/4268/2897"; },
        [](const DemId& d) { return d.z == 12 && d.x % 2 == 0; }, 60);
    const auto& want = fx["plan"]["keys"].arr();
    CHECK(plan.size() == want.size());
    for (size_t k = 0; k < std::min(plan.size(), want.size()); k++) CHECK(demKey(plan[k]) == want[k].str());
  }
}

// ---- scene parity (#551 redesign) ----------------------------------------------------
static Mat4 refProjection(double lng, double lat, double zoom, double pitchDeg, double bearingDeg,
                          double w, double h);

static void testScene(const Json& fx) {
  const auto& sc = fx["scene"];
  for (const auto& c : sc["contours"].arr()) {
    g_cases++;
    const double h = c[0].num(), d = c[1].num(), z = c[2].num();
    const auto [mn, mj] = contourAt(h, d, z);
    CHECK_NEAR(mn, c[3].num(), 1e-9);
    CHECK_NEAR(mj, c[4].num(), 1e-9);
    const auto [idx, fw] = levelForDensity(static_cast<int>(z) % 3, d);
    CHECK(idx == static_cast<int>(c[5].num()));
    CHECK_NEAR(fw, c[6].num(), 1e-9);
  }
  auto hex = [](int r, int g, int b) { return Rgb{r / 255.0, g / 255.0, b / 255.0}; };
  const Rgb land = hex(0xf2, 0xec, 0xe0), alt = hex(0xe6, 0xdf, 0xcf);
  auto mixc = [](const Rgb& a, const Rgb& b, double t) {
    return Rgb{a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t, a[2] + (b[2] - a[2]) * t};
  };
  SurfacePalette pal;
  pal.land = land;
  pal.rock = alt;
  pal.water = mixc(land, hex(0x5c, 0x93, 0xb7), 0.45);
  pal.glacier = mixc(Rgb{1, 1, 1}, hex(0x5c, 0x93, 0xb7), 0.16);
  pal.shadow = mixc(land, hex(74, 62, 45), 0.78);
  pal.highlight = mixc(land, Rgb{1, 250 / 255.0, 240 / 255.0}, 0.9);
  for (const auto& r : sc["surface"].arr()) {
    g_cases++;
    const Rgb c = shadeSurface(pal, SurfaceParams{}, r[0].num(), r[1].num(), r[2].num(), 1.3,
                               lightDirection(20), r[3].num(), r[4].num());
    for (int k = 0; k < 3; k++) CHECK_NEAR(c[k], r[5 + k].num(), 1e-9);
  }
  {
    struct Mulberry {
      uint32_t a;
      double next() {
        a += 0x6d2b79f5u;
        uint32_t t = a;
        t = (t ^ (t >> 15)) * (t | 1u);
        t ^= t + (t ^ (t >> 7)) * (t | 61u);
        return (t ^ (t >> 14)) / 4294967296.0;
      }
    } r{7};
    const double lng = 6.8694, lat = 45.9237, zoom = 13, W = 412, H = 892;
    const Mat4 P = refProjection(lng, lat, zoom, 65, 30, W, H);
    const double ws = worldSize(zoom);
    const double cx = lngToMercX(lng) * ws, cy = latToMercY(lat) * ws;
    std::vector<LabelInput> inputs;
    for (int i = 0; i < 30; i++) {
      LabelInput l;
      l.id = i;
      l.x = cx + (r.next() - 0.5) * 900;
      l.y = cy + (r.next() - 0.5) * 900 - 300;
      l.h = 1000 + r.next() * 2500;
      l.priority = std::floor(r.next() * 10);
      l.w = 60 + std::floor(r.next() * 60);
      l.ph = 22;
      inputs.push_back(l);
    }
    std::unordered_map<int, LabelState> states;
    const auto& frames = sc["labelFrames"].arr();
    for (int f = 0; f < 4; f++) {
      g_cases++;
      PlaceOptions o;
      o.P = P;
      o.width = W;
      o.height = H;
      o.ctc = cameraToCenterDistance(H, 0.6435011087932844);
      o.hRef = 1100;
      o.heightScale = 1.2;
      o.dtMs = 70;
      o.nowMs = f * 70;
      o.occluded = [](const LabelInput& l) { return l.id % 7 == 3; };
      std::vector<LabelInput> sub(inputs.begin(), inputs.begin() + (30 - f * 3));
      const auto placed = placeLabels(sub, states, o);
      if (f == 0) {
        // UI bands covering the whole screen hide every plate (labels.ts parity).
        PlaceOptions banded = o;
        banded.topPx = H / 2;
        banded.bottomPx = H / 2;
        std::unordered_map<int, LabelState> fresh;
        banded.dtMs = 1000;
        CHECK(placeLabels(sub, fresh, banded).empty());
      }
      const auto& want = frames[f].arr();
      CHECK(placed.size() == want.size());
      for (size_t k = 0; k < std::min(placed.size(), want.size()); k++) {
        const auto& p = placed[k];
        const auto& wv = want[k];
        CHECK(p.id == static_cast<int>(wv[0].num()));
        const double vals[] = {p.ax, p.ay, p.depth, p.cx, p.cy, p.gx, p.gy, p.scale, p.opacity};
        for (int j = 0; j < 9; j++)
          CHECK_NEAR(vals[j], wv[j + 1].num(), 1e-6 * std::max(1.0, std::abs(wv[j + 1].num())));
      }
    }
  }
  {
    g_cases++;
    const auto& oc = sc["occl"].arr();
    const Vec3 eye{0, 0, 3000}, anchor{1000, 0, 0};
    CHECK(occludedByTerrain(eye, anchor, [](double x, double) -> std::optional<double> {
            return (x > 400 && x < 600) ? 2500.0 : 0.0;
          }) == oc[0].boolean());
    CHECK(occludedByTerrain(eye, anchor,
                            [](double, double) -> std::optional<double> { return 0.0; }) ==
          oc[1].boolean());
    CHECK(occludedByTerrain(eye, anchor, [](double x, double) -> std::optional<double> {
            if (x > 980) return 900.0;
            return std::nullopt;
          }) == oc[2].boolean());
  }
  {
    g_cases++;
    const auto d = densify({{0, 0}, {0.003, 0.001}, {0.0031, 0.0042}}, 0.0004);
    const auto& want = sc["dens"].arr();
    CHECK(d.size() == want.size());
    for (size_t k = 0; k < std::min(d.size(), want.size()); k++) {
      CHECK_NEAR(d[k][0], want[k][0].num(), 1e-15);
      CHECK_NEAR(d[k][1], want[k][1].num(), 1e-15);
    }
    const auto e0 = extrudeOffset({-0.2, 0.1}, {0.4, 0.3}, 1, 3, {400, 800});
    const auto e1 = extrudeOffset({0.5, 0.5}, {0.5, -0.5}, -1, 6, {1080, 2400});
    CHECK_NEAR(e0[0], sc["ext"][0][0].num(), 1e-12);
    CHECK_NEAR(e0[1], sc["ext"][0][1].num(), 1e-12);
    CHECK_NEAR(e1[0], sc["ext"][1][0].num(), 1e-12);
    CHECK_NEAR(e1[1], sc["ext"][1][1].num(), 1e-12);
    const auto m = rasterizePolygons({{{0.1, 0.05}, {0.9, 0.2}, {0.7, 0.95}, {0.05, 0.6}},
                                      {{0.3, 0.3}, {0.5, 0.35}, {0.4, 0.55}}},
                                     32);
    bool same = m.size() == sc["mask"].arr().size();
    for (size_t k = 0; same && k < m.size(); k++)
      same = m[k] == static_cast<uint8_t>(sc["mask"][k].num());
    CHECK(same);
  }
}

// ---- PNG -------------------------------------------------------------------------
static void putBe32(std::vector<uint8_t>& v, uint32_t x) {
  v.push_back(x >> 24);
  v.push_back((x >> 16) & 0xff);
  v.push_back((x >> 8) & 0xff);
  v.push_back(x & 0xff);
}
static void chunk(std::vector<uint8_t>& png, const char* type, const std::vector<uint8_t>& body) {
  putBe32(png, static_cast<uint32_t>(body.size()));
  std::vector<uint8_t> tb(type, type + 4);
  tb.insert(tb.end(), body.begin(), body.end());
  png.insert(png.end(), tb.begin(), tb.end());
  putBe32(png, static_cast<uint32_t>(crc32(0, tb.data(), static_cast<uInt>(tb.size()))));
}
static int paethP(int a, int b, int c) {
  const int p = a + b - c, pa = std::abs(p - a), pb = std::abs(p - b), pc = std::abs(p - c);
  if (pa <= pb && pa <= pc) return a;
  return pb <= pc ? b : c;
}
/** Encode an image with a given filter per row (to exercise the unfilter). */
static std::vector<uint8_t> encodePng(int w, int h, int colorType, const std::vector<uint8_t>& px,
                                      const std::vector<int>& filters, int splitIdat = 1) {
  const int bpp = colorType == 2 ? 3 : colorType == 6 ? 4 : colorType == 0 ? 1 : 2;
  const size_t stride = static_cast<size_t>(w) * bpp;
  std::vector<uint8_t> raw;
  for (int y = 0; y < h; y++) {
    const int f = filters[y % filters.size()];
    raw.push_back(static_cast<uint8_t>(f));
    for (size_t i = 0; i < stride; i++) {
      const int x = px[y * stride + i];
      const int a = i >= static_cast<size_t>(bpp) ? px[y * stride + i - bpp] : 0;
      const int b = y > 0 ? px[(y - 1) * stride + i] : 0;
      const int c = (y > 0 && i >= static_cast<size_t>(bpp)) ? px[(y - 1) * stride + i - bpp] : 0;
      int v = x;
      if (f == 1) v = x - a;
      if (f == 2) v = x - b;
      if (f == 3) v = x - ((a + b) >> 1);
      if (f == 4) v = x - paethP(a, b, c);
      raw.push_back(static_cast<uint8_t>(v & 0xff));
    }
  }
  uLongf zlen = compressBound(static_cast<uLong>(raw.size()));
  std::vector<uint8_t> z(zlen);
  compress(z.data(), &zlen, raw.data(), static_cast<uLong>(raw.size()));
  z.resize(zlen);
  std::vector<uint8_t> png = {0x89, 'P', 'N', 'G', '\r', '\n', 0x1a, '\n'};
  std::vector<uint8_t> ihdr;
  putBe32(ihdr, w);
  putBe32(ihdr, h);
  ihdr.insert(ihdr.end(), {8, static_cast<uint8_t>(colorType), 0, 0, 0});
  chunk(png, "IHDR", ihdr);
  const size_t part = (z.size() + splitIdat - 1) / splitIdat;
  for (size_t o = 0; o < z.size(); o += part)
    chunk(png, "IDAT", std::vector<uint8_t>(z.begin() + o, z.begin() + std::min(z.size(), o + part)));
  chunk(png, "IEND", {});
  return png;
}

static void testPng() {
  std::mt19937 rnd(5);
  for (int colorType : {0, 2, 4, 6}) {
    for (const std::vector<int>& filters :
         std::vector<std::vector<int>>{{0}, {1}, {2}, {3}, {4}, {0, 1, 2, 3, 4}, {4, 3, 2, 1}}) {
      for (int split : {1, 3}) {
        g_cases++;
        const int w = 37, h = 23;
        const int bpp = colorType == 2 ? 3 : colorType == 6 ? 4 : colorType == 0 ? 1 : 2;
        std::vector<uint8_t> px(static_cast<size_t>(w) * h * bpp);
        for (auto& b : px) b = static_cast<uint8_t>(rnd() & 0xff);
        auto png = encodePng(w, h, colorType, px, filters, split);
        DecodedImage img;
        std::string err;
        CHECK(decodePng(png.data(), png.size(), img, err));
        CHECK(img.width == w && img.height == h);
        const int outC = (colorType == 6 || colorType == 4) ? 4 : 3;
        CHECK(img.channels == outC);
        bool same = true;
        for (int i = 0; i < w * h; i++) {
          for (int c = 0; c < outC; c++) {
            int want;
            if (colorType == 2 || colorType == 6) want = px[i * bpp + c];
            else if (c < 3) want = px[i * bpp];
            else want = px[i * bpp + 1];
            if (img.pixels[i * outC + c] != want) same = false;
          }
        }
        CHECK(same);
      }
    }
  }
  // Rejections.
  DecodedImage img;
  std::string err;
  const uint8_t junk[] = {1, 2, 3};
  CHECK(!decodePng(junk, sizeof junk, img, err));
  std::vector<uint8_t> px(16 * 16 * 3, 7);
  auto png = encodePng(16, 16, 2, px, {0});
  auto truncated = std::vector<uint8_t>(png.begin(), png.begin() + 40);
  CHECK(!decodePng(truncated.data(), truncated.size(), img, err));
  auto badFilter = png;
  // corrupt IHDR colour type to palette (3) → unsupported
  badFilter[8 + 8 + 9] = 3;
  CHECK(!decodePng(badFilter.data(), badFilter.size(), img, err));
  g_cases += 3;

  // A Terrarium round-trip through PNG → heights.
  std::vector<uint8_t> dem(256 * 256 * 3);
  for (int i = 0; i < 256 * 256; i++) {
    const double hm = 1000 + (i % 256) * 3.5 + (i / 256) * 1.25;
    const double v = hm + 32768;
    const int r = static_cast<int>(v / 256), g = static_cast<int>(v - r * 256);
    const int b = static_cast<int>(std::lround((v - r * 256 - g) * 256)) & 0xff;
    dem[i * 3] = r;
    dem[i * 3 + 1] = g;
    dem[i * 3 + 2] = b;
  }
  auto demPng = encodePng(256, 256, 2, dem, {0, 1, 2, 3, 4});
  CHECK(decodePng(demPng.data(), demPng.size(), img, err));
  auto hs = decodeTerrarium(img.pixels.data(), 256, 256, 3);
  CHECK_NEAR(hs[0], 1000, 0.01);
  CHECK_NEAR(hs[255], 1000 + 255 * 3.5, 0.01);
  CHECK_NEAR(hs[256 * 100 + 7], 1000 + 7 * 3.5 + 125, 0.01);
  g_cases++;
}

// ---- engine -----------------------------------------------------------------------
static Mat4 refProjection(double lng, double lat, double zoom, double pitchDeg, double bearingDeg,
                          double w, double h) {
  // Same construction as src/core/terrain3d/camera.ts (lookAt + perspective + flip/scale).
  const double fov = 0.6435011087932844;
  const double pitch = pitchDeg * kPi / 180, bearing = bearingDeg * kPi / 180;
  const double ctc = cameraToCenterDistance(h, fov);
  const double ws = worldSize(zoom);
  const double cx = lngToMercX(lng) * ws, cy = latToMercY(lat) * ws;
  const double fX = std::sin(bearing), fY = std::cos(bearing);
  const Vec3 target{cx, -cy, 0};
  const Vec3 eye{cx - fX * ctc * std::sin(pitch), -cy - fY * ctc * std::sin(pitch), ctc * std::cos(pitch)};
  const Vec3 up{fX * std::cos(pitch), fY * std::cos(pitch), std::sin(pitch)};
  double f[3] = {target[0] - eye[0], target[1] - eye[1], target[2] - eye[2]};
  double fl = std::hypot(f[0], f[1], f[2]);
  for (double& x : f) x /= fl;
  double s[3] = {f[1] * up[2] - f[2] * up[1], f[2] * up[0] - f[0] * up[2], f[0] * up[1] - f[1] * up[0]};
  double sl = std::hypot(s[0], s[1], s[2]);
  for (double& x : s) x /= sl;
  double u[3] = {s[1] * f[2] - s[2] * f[1], s[2] * f[0] - s[0] * f[2], s[0] * f[1] - s[1] * f[0]};
  Mat4 view = {s[0], u[0], -f[0], 0, s[1], u[1], -f[1], 0, s[2], u[2], -f[2], 0,
               -(s[0] * eye[0] + s[1] * eye[1] + s[2] * eye[2]),
               -(u[0] * eye[0] + u[1] * eye[1] + u[2] * eye[2]),
               f[0] * eye[0] + f[1] * eye[1] + f[2] * eye[2], 1};
  const double limited = std::min(std::max(pitch, 0.0), 85 * kPi / 180);
  const double tm = std::min(std::max(std::tan(fov / 2) * std::tan(limited), 0.0), 0.99);
  const double farZ = ctc / (1 - tm) * 1.01, nearZ = 1;
  const double ff = 1 / std::tan(fov / 2), nf = 1 / (nearZ - farZ);
  Mat4 proj = {ff / (w / h), 0, 0, 0, 0, ff, 0, 0, 0, 0, (farZ + nearZ) * nf, -1, 0, 0, 2 * farZ * nearZ * nf, 0};
  return multiply(multiply(proj, view), scaling(1, -1, pixelsPerMeter(lat, zoom)));
}

static void testEngine() {
  std::vector<DemId> requested;
  int repaints = 0;
  std::vector<DemId> imgRequested;
  Engine eng([&](int z, int x, int y) { requested.push_back({z, x, y}); },
             [&](int z, int x, int y) { imgRequested.push_back({z, x, y}); }, [&] { repaints++; });
  const double lng = 7.7491, lat = 46.0207, zoom = 13, w = 412, h = 892;
  FrameInput in;
  in.P = refProjection(lng, lat, zoom, 60, 20, w, h);
  in.width = w;
  in.height = h;
  in.zoom = zoom;
  in.lat = lat;
  in.lng = lng;
  in.bearingDeg = 20;
  in.pitchDeg = 60;
  in.timeMs = 1000;

  // 1. Flat below the ramp: no work at all.
  {
    g_cases++;
    FrameInput flat = in;
    flat.pitchDeg = 10;
    auto out = eng.frame(flat);
    CHECK(!out.active);
    CHECK(out.tiles.empty());
    CHECK(requested.empty());
  }
  // 2. First tilted frame, no DEM: every tile draws flat, DEM requests go out.
  auto out = eng.frame(in);
  {
    g_cases++;
    CHECK(out.active);
    CHECK_NEAR(out.ramp, 1, 1e-6);
    CHECK(!out.tiles.empty());
    for (const auto& t : out.tiles) {
      CHECK(t.attributes == nullptr);
      CHECK(t.fromFlat == 1);
    }
    CHECK(static_cast<int>(requested.size()) == Engine::kRequestsPerFrame);
    // coarse ancestors first
    CHECK(requested[0].z <= requested[1].z);
  }
  // 3. DEMs arrive (synthetic heights) → tiles bake and morph in from flat.
  auto synth = [](const DemId& d) {
    std::vector<float> hs(kDemSize * kDemSize);
    for (int j = 0; j < kDemSize; j++)
      for (int i = 0; i < kDemSize; i++) {
        const double mx = (d.x + (i + 0.5) / kDemSize) / std::pow(2.0, d.z);
        const double my = (d.y + (j + 0.5) / kDemSize) / std::pow(2.0, d.z);
        hs[j * kDemSize + i] = static_cast<float>(1500 + 1200 * std::sin(mx * 4000) * std::cos(my * 3000));
      }
    return hs;
  };
  for (int round = 0; round < 40 && !requested.empty(); round++) {
    auto batch = requested;
    requested.clear();
    for (const auto& d : batch) eng.onDemHeights(d.z, d.x, d.y, synth(d));
    in.timeMs += 16;
    eng.frame(in);  // schedules bakes
    eng.drainBakes();
    in.timeMs += 16;
    out = eng.frame(in);  // installs them
  }
  for (int i = 0; i < 6; i++) {
    eng.drainBakes();
    in.timeMs += 16;
    out = eng.frame(in);
  }
  {
    g_cases++;
    CHECK(repaints > 0);
    int withMesh = 0;
    for (const auto& t : out.tiles) withMesh += t.attributes != nullptr;
    CHECK(withMesh == static_cast<int>(out.tiles.size()));
    auto st = eng.stats();
    CHECK(st.demCount > 0);
    CHECK(st.demBytes <= Engine::kDemBudgetBytes || st.demCount > 0);
    CHECK(st.flatTiles == 0);
  }
  // 4. Morphs settle; a settled frame doesn't ask for a repaint.
  {
    g_cases++;
    for (int i = 0; i < 120; i++) {
      eng.drainBakes();
      in.timeMs += 16;
      out = eng.frame(in);
    }
    for (const auto& t : out.tiles) CHECK(t.morph == 0);
    CHECK(!out.needsRepaint);
  }
  // 5. Attribute sanity: hTo equals the synthetic surface at a vertex.
  {
    g_cases++;
    const auto& t = out.tiles.front();
    CHECK(t.attributes->size() == static_cast<size_t>(vertexCount(kGrid) * kAttributesPerVertex));
    bool finite = true;
    for (float v : *t.attributes) finite = finite && std::isfinite(v);
    CHECK(finite);
  }
  // 5b. A finer mesh grid bakes finer meshes over the same tile selection.
  {
    g_cases++;
    std::vector<DemId> req64;
    Engine fine([&](int z, int x, int y) { req64.push_back({z, x, y}); }, nullptr, nullptr, 64);
    CHECK(fine.meshGrid() == 64);
    FrameInput fi = in;
    FrameOutput fo = fine.frame(fi);
    for (int round = 0; round < 40 && !req64.empty(); round++) {
      auto batch = req64;
      req64.clear();
      for (const auto& d : batch) fine.onDemHeights(d.z, d.x, d.y, synth(d));
      fi.timeMs += 16;
      fine.frame(fi);
      fine.drainBakes();
      fi.timeMs += 16;
      fo = fine.frame(fi);
    }
    CHECK(fo.tiles.size() == out.tiles.size());
    bool all64 = !fo.tiles.empty();
    for (const auto& t : fo.tiles)
      all64 = all64 && t.attributes &&
              t.attributes->size() == static_cast<size_t>(vertexCount(64) * kAttributesPerVertex);
    CHECK(all64);
  }
  // 6. hRef sits on the synthetic range and is smooth.
  {
    g_cases++;
    CHECK(out.hRef > 300 && out.hRef < 2700);
  }
  // 7. Panning keeps versions of cached tiles; new tiles morph from parents.
  {
    g_cases++;
    std::map<uint64_t, uint32_t> versions;
    for (const auto& t : out.tiles) versions[t.key] = t.version;
    FrameInput moved = in;
    moved.P = refProjection(lng + 0.01, lat, zoom, 60, 20, w, h);
    moved.timeMs += 16;
    auto o2 = eng.frame(moved);
    int kept = 0;
    for (const auto& t : o2.tiles)
      if (versions.count(t.key) && versions[t.key] == t.version) kept++;
    CHECK(kept > 0);
  }
  // 8. Low memory drops unpinned DEMs but keeps what's on screen drawable.
  {
    g_cases++;
    std::map<uint64_t, bool> before;
    for (const auto& t : out.tiles) before[t.key] = t.attributes != nullptr;
    const int demsBefore = eng.stats().demCount;
    eng.trimMemory();
    CHECK(eng.stats().demCount < demsBefore);
    const int meshesBefore = eng.stats().meshCount;
    in.timeMs += 16;
    auto o3 = eng.frame(in);
    CHECK(!o3.tiles.empty());
    // Every tile that had a mesh before the warning still draws it.
    for (const auto& t : o3.tiles)
      if (before.count(t.key) && before[t.key]) CHECK(t.attributes != nullptr);
    CHECK(eng.stats().flatTiles == 0);
    CHECK(eng.stats().meshCount <= meshesBefore);
    CHECK(eng.stats().meshCount <= static_cast<int>(o3.tiles.size()) + Engine::kMaxBakeJobs);
    // Culled neighbours lose their (unpinned) height bounds, so the walk may
    // admit a few more tiles — never a flat one.
    CHECK(o3.tiles.size() <= out.tiles.size() * 5 / 4);
  }
  // 9. Failures back off (no immediate re-request).
  {
    g_cases++;
    Engine e2([&](int z, int x, int y) { requested.push_back({z, x, y}); }, nullptr, [] {});
    requested.clear();
    e2.frame(in);
    auto first = requested;
    for (const auto& d : first) e2.onDemFailed(d.z, d.x, d.y);
    requested.clear();
    in.timeMs += 16;
    e2.frame(in);
    for (const auto& d : requested)
      for (const auto& f : first) CHECK(!(d == f));
    CHECK(e2.stats().failed == static_cast<int>(first.size()));
  }
  // 10. Bad PNG bytes count as a failure.
  {
    g_cases++;
    const uint8_t junk[] = {0, 1, 2, 3};
    CHECK(!eng.onDemData(5, 1, 1, junk, sizeof junk));
  }
  // 11. Reset clears meshes on the next frame.
  {
    g_cases++;
    eng.reset();
    in.timeMs += 16;
    auto o4 = eng.frame(in);
    for (const auto& t : o4.tiles) CHECK(t.attributes == nullptr);
  }
  // 12. heightAt reads the deepest loaded DEM.
  {
    g_cases++;
    Engine e3(nullptr, nullptr, nullptr);
    std::vector<float> hs(kDemSize * kDemSize, 1234.f);
    e3.onDemHeights(0, 0, 0, hs);
    auto hv = e3.heightAt(0.3, 0.6, 15);
    CHECK(hv.has_value());
    CHECK_NEAR(*hv, 1234, 1e-3);
    CHECK(!e3.heightAt(0.3, 1.2, 15).has_value());
  }
  // 13. Sky rays point up at the top of a steep view.
  {
    g_cases++;
    FrameInput steep = in;
    steep.pitchDeg = 80;
    steep.P = refProjection(lng, lat, zoom, 80, 20, w, h);
    auto o5 = eng.frame(steep);
    const float* top = o5.skyRays[2];  // (-1, 3): above the top edge
    const float* bottom = o5.skyRays[0];
    CHECK(top[2] / top[3] > bottom[2] / bottom[3]);
  }
  // ---- the 3D scene (#551 redesign) ----
  // A fresh engine with every DEM delivered synchronously.
  std::vector<DemId> req2, img2;
  Engine sc([&](int z, int x, int y) { req2.push_back({z, x, y}); },
            [&](int z, int x, int y) { img2.push_back({z, x, y}); }, nullptr);
  auto settle = [&](FrameInput fi, int frames) {
    FrameOutput o;
    for (int i = 0; i < frames; i++) {
      auto batch = req2;
      req2.clear();
      for (const auto& d : batch) sc.onDemHeights(d.z, d.x, d.y, synth(d));
      sc.drainBakes();
      fi.timeMs += 16;
      o = sc.frame(fi);
    }
    return o;
  };
  in.P = refProjection(lng, lat, zoom, 60, 20, w, h);
  in.pitchDeg = 60;
  FrameOutput so = settle(in, 40);
  // 14. Every drawn mesh carries a detail texture of the right size.
  {
    g_cases++;
    int withDetail = 0;
    for (const auto& t : so.tiles) {
      if (!t.attributes) continue;
      CHECK(t.detail != nullptr);
      if (t.detail) {
        CHECK(t.detail->size() == static_cast<size_t>(kDetailSize * kDetailSize * 4));
        withDetail++;
      }
    }
    CHECK(withDetail > 0);
    CHECK(so.contourBase == baseLevelIndex(zoom));
  }
  // 15. Masks: a lake polygon over the view lands in the water channel after a re-bake.
  {
    g_cases++;
    const double cxm = lngToMercX(lng), cym = latToMercY(lat);
    const double r = 0.0004;
    sc.setMasks({{{cxm - r, cym - r}, {cxm + r, cym - r}, {cxm + r, cym + r}, {cxm - r, cym + r}}},
                {});
    so = settle(in, 30);
    int waterPx = 0;
    for (const auto& t : so.tiles)
      if (t.detail)
        for (size_t k = 2; k < t.detail->size(); k += 4) waterPx += (*t.detail)[k] > 0;
    CHECK(waterPx > 0);
  }
  // 16. Labels: placed, faded in, the more important one wins a shared spot.
  {
    g_cases++;
    const double cxm = lngToMercX(lng), cym = latToMercY(lat);
    std::vector<LabelData> ls;
    for (int i = 0; i < 2; i++) {
      LabelData d;
      d.id = 100 + i;
      d.mercX = cxm + i * 1e-7;
      d.mercY = cym - 0.0001;
      d.priority = i == 0 ? 5 : 1;
      d.w = 90;
      d.h = 26;
      d.u1 = d.v1 = 0.1f;
      ls.push_back(d);
    }
    LabelData far;
    far.id = 200;
    far.mercX = cxm + 0.0006;
    far.mercY = cym - 0.0002;
    far.priority = 9;
    far.w = 60;
    far.h = 24;
    ls.push_back(far);
    sc.setLabels(ls);
    so = settle(in, 30);
    std::set<int> shown;
    for (const auto& l : so.labels)
      if (l.opacity > 0.99) shown.insert(l.id);
    CHECK(shown.count(101) == 1);
    CHECK(shown.count(100) == 0);
    for (const auto& l : so.labels) {
      CHECK(l.x1 > l.x0);
      CHECK(l.y1 > l.y0);
      CHECK(l.y1 <= l.gy);  // the plate sits above its ground point
    }
  }
  // 17. Polylines: lifted onto the terrain (heights from the DEM), 6 vertices per segment.
  {
    g_cases++;
    const double cxm = lngToMercX(lng), cym = latToMercY(lat);
    sc.setPolyline(7, {{cxm - 0.0003, cym}, {cxm + 0.0003, cym + 0.0001}}, LineStyle{});
    so = settle(in, 3);
    CHECK(so.lines.size() == 1);
    if (!so.lines.empty()) {
      const auto& v = *so.lines[0].vertices;
      CHECK(v.size() % (6 * 8) == 0);
      CHECK(v.size() / (6 * 8) > 10);  // densified (~15 m steps)
      const auto ground = sc.heightAt(cxm - 0.0003, cym, kDemMaxZoom);
      CHECK(ground.has_value());
      if (ground) CHECK_NEAR(v[2], *ground, 1e-2);
    }
    sc.removePolyline(7);
    so = settle(in, 1);
    CHECK(so.lines.empty());
  }
  // 18. The location marker projects inside the view.
  {
    g_cases++;
    sc.setPuck(true, lngToMercX(lng), latToMercY(lat));
    so = settle(in, 1);
    CHECK(so.puck.visible);
    CHECK(so.puck.gx > 0 && so.puck.gx < w && so.puck.gy > 0 && so.puck.gy < h);
    sc.setPuck(false, 0, 0);
    so = settle(in, 1);
    CHECK(!so.puck.visible);
  }
  // 19. Satellite: imagery requested, uploaded into slots, tiles sample their slot.
  {
    g_cases++;
    LookParams lp;
    lp.imagery = 1;
    sc.setLook(lp);
    img2.clear();
    so = settle(in, 2);
    CHECK(!img2.empty());
    for (int round = 0; round < 30 && !img2.empty(); round++) {
      auto batch = img2;
      img2.clear();
      for (const auto& d : batch)
        sc.onImageryData(d.z, d.x, d.y, std::vector<uint8_t>(kImagerySize * kImagerySize * 4, 128));
      so = settle(in, 1);
    }
    so = settle(in, 40);
    int withImg = 0;
    for (const auto& t : so.tiles) withImg += t.imgB >= 0;
    CHECK(withImg > 0);
    CHECK(sc.stats().imagerySlots > 0);
    CHECK(sc.stats().imagerySlots <= Engine::kImagerySlots);
    // Bad imagery sizes are rejected.
    sc.onImageryData(3, 1, 1, std::vector<uint8_t>(10, 0));
  }
  // 20. The look round-trips through its float packing.
  {
    g_cases++;
    float v[41];
    for (int i = 0; i < 41; i++) v[i] = static_cast<float>(i) / 100;
    v[40] = 2;
    const LookParams l = lookFromFloats(v, 41);
    CHECK_NEAR(l.exaggeration, 0, 1e-9);
    CHECK_NEAR(l.fogEndCtc, 0.13, 1e-6);
    CHECK_NEAR(l.land[0], 0.14, 1e-6);
    CHECK_NEAR(l.highlight[2], 0.31, 1e-6);
    CHECK_NEAR(l.contourMajor[2], 0.37, 1e-6);
    CHECK_NEAR(l.contourOpacity, 0.38, 1e-6);
    CHECK_NEAR(l.imagery, 0.39, 1e-6);
    CHECK(l.debugFlags == 2);
    CHECK(lookFromFloats(v, 12).exaggeration == LookParams{}.exaggeration);
  }
  // 21. Drape mode: per-tile textures with mip chains, generations, slot bound.
  {
    g_cases++;
    LookParams lp;  // the map look (no satellite flag): the drape alone turns imagery on
    sc.setLook(lp);
    sc.setDrape(true, 24);
    const uint32_t gen = sc.imageryGeneration();
    img2.clear();
    so = settle(in, 2);
    CHECK(so.drape);
    CHECK(!img2.empty());
    std::vector<uint8_t> px(64 * 64 * 4, 200);
    int levels = 0;
    for (int round = 0; round < 30 && !img2.empty(); round++) {
      auto batch = img2;
      img2.clear();
      for (const auto& d : batch)
        sc.onImageryLevels(d.z, d.x, d.y, buildMipChain(px.data(), 64, levels), 64, levels, gen);
      so = settle(in, 1);
    }
    int withImg = 0;
    for (const auto& t : so.tiles) withImg += t.imgB >= 0;
    CHECK(withImg > 0);
    CHECK(sc.stats().imagerySlots <= 24);
    // A stale generation is dropped; a reset frees every slot.
    sc.resetImagery();
    CHECK(sc.imageryGeneration() == gen + 1);
    sc.onImageryLevels(3, 1, 1, buildMipChain(px.data(), 64, levels), 64, levels, gen);
    so = settle(in, 1);
    for (const auto& u : so.imageryUploads) CHECK(u.size == 64);
    sc.setDrape(false, 24);
  }
  // 22. Mip chains: level count, packing, box filter.
  {
    g_cases++;
    CHECK(mipLevelCount(1) == 1);
    CHECK(mipLevelCount(512) == 10);
    CHECK(mipChainBytes(4, 3) == (16 + 4 + 1) * 4u);
    std::vector<uint8_t> px(4 * 4 * 4, 0);
    for (int i = 0; i < 16; i++) px[i * 4] = static_cast<uint8_t>(i < 8 ? 0 : 255);  // top black, bottom red
    int levels = 0;
    const auto chain = buildMipChain(px.data(), 4, levels);
    CHECK(levels == 3);
    CHECK(chain.size() == mipChainBytes(4, 3));
    CHECK(chain[64] == 0);           // level 1 (2×2), top-left
    CHECK(chain[64 + 2 * 4] == 255);  // level 1, bottom-left
    CHECK(chain[80] == 128);          // level 2 (1×1): the average
    CHECK(buildMipChain(px.data(), 3, levels).empty());
  }

}

int main(int argc, char** argv) {
  const std::string path = argc > 1 ? argv[1] : "fixtures/parity.json";
  std::ifstream f(path);
  if (!f) {
    std::fprintf(stderr, "cannot open %s\n", path.c_str());
    return 2;
  }
  std::stringstream ss;
  ss << f.rdbuf();
  const std::string text = ss.str();
  Parser p{text};
  const Json fx = p.parse();
  testParity(fx);
  testScene(fx);
  testPng();
  testEngine();
  std::printf("terrain C++ tests: %d cases, %d checks, %d failures\n", g_cases, g_checks, g_failures);
  return g_failures == 0 ? 0 : 1;
}
