/**
 * The tide-station catalogue the tiles index into (sources, chart-datum
 * kinds, level names). Generated by `infra/tiles/nas/tides/catalog.py`; the
 * pipeline's tests fail when this JSON and the build drift. Sources are
 * APPEND-ONLY (tiles carry the index `s`).
 *
 * CHS (Canada) is not in it on purpose: owner decision 2026-10-05 (PLAN Q1 =
 * c) keeps CHS live-only; its data is never in our tiles.
 */
import raw from './catalog-v1.json';

export interface TideSource {
  key: string;
  name: string;
  network: string;
  licence: string;
  /** Card footer credit, verbatim. */
  attribution: string;
  licenceUrl: string;
  /** Station page; `{id}` = the tile's `i`. */
  page: string;
  /** The agency's own caution, shown on every card. */
  disclaimer: string;
}

export interface CdKind {
  key: string;
  /** Short label (table column header), e.g. "MLLW", "ZH". */
  label: string;
  description: string;
}

export interface TideCatalog {
  version: number;
  sources: TideSource[];
  cdKinds: CdKind[];
  levels: Record<string, string>;
  national: Record<string, string>;
}

export const TIDE_CATALOG: TideCatalog = raw;

export function tideSourceAt(index: number | undefined): TideSource | undefined {
  return index === undefined ? undefined : TIDE_CATALOG.sources[index];
}

export function cdKind(key: string | undefined): CdKind | undefined {
  return TIDE_CATALOG.cdKinds.find((c) => c.key === key);
}

/** "IGN69" → "NGF-IGN69"; an unknown datum name passes through as published. */
export function nationalName(datum: string): string {
  return TIDE_CATALOG.national[datum] ?? datum;
}

/** The English name of a level code (agency acronyms kept as published). */
export function levelName(code: string): string | undefined {
  return TIDE_CATALOG.levels[code];
}
