/**
 * Map-store catalog manifest — schema v1 types + a total parser.
 *
 * The manifest is a static JSON document generated by `scripts/catalog/` and
 * hosted on the Pages site (`/catalog/v1/manifest.json`). This module is the
 * single source of truth for its shape: the app parses fetched manifests with
 * {@link parseCatalogManifest}, and the generator validates its own output with
 * the same function before writing — so app and generator cannot drift.
 *
 * Parser contract (mirrors `parseGeoPdf` / the migration ladder): any JSON
 * value in, never throws. A fundamentally unusable document (not an object,
 * wrong `schemaVersion`, no item array) yields `manifest: null` with a reason
 * in `warnings`; malformed entries in an otherwise sound manifest are dropped
 * item-by-item with a warning each, so one bad row can never blank the store.
 */

/** The manifest schema this client reads. Breaking changes bump the /vN/ path. */
export const CATALOG_SCHEMA_VERSION = 1;

/** Store categories (fixed vocabulary; the generator emits only these). */
export const CATALOG_CATEGORIES = [
  'topo',
  'parks',
  'geological',
  'aerial',
  'forest',
  'hunting',
  'touristic',
  'nautical',
  'river',
] as const;

export type CatalogCategory = (typeof CATALOG_CATEGORIES)[number];

/** Chip/UI label per category. */
export const CATALOG_CATEGORY_LABELS: Record<CatalogCategory, string> = {
  topo: 'Topo',
  parks: 'Parks',
  geological: 'Geological',
  aerial: 'Aerial',
  forest: 'Forest',
  hunting: 'Hunting',
  touristic: 'Touristic',
  nautical: 'Nautical',
  river: 'River runs',
};

/** File formats this client can land in the Library. GeoTIFF is deferred (M3). */
export const SUPPORTED_FORMATS = ['geopdf', 'pdf'] as const;
export type CatalogFormat = (typeof SUPPORTED_FORMATS)[number];

/** How the downloaded bytes are wrapped. CanTopo serves its GeoPDFs zipped. */
export type CatalogPackaging = 'none' | 'zip';

/** A publisher whose products the catalog links to (attribution + licence). */
export interface CatalogSource {
  id: string;
  name: string;
  /** SPDX-ish licence label shown verbatim, e.g. "OGL-Canada-2.0". */
  licence: string;
  /** Attribution line shown in the item detail, e.g. "Natural Resources Canada". */
  attribution: string;
  homepage?: string;
}

/** WGS84 [west, south, east, north]. */
export type CatalogBbox = [number, number, number, number];

/** One downloadable product. */
export interface CatalogItem {
  /** Stable id: source + native sheet/product id, e.g. "cantopo-021l14". */
  id: string;
  /** Id of the {@link CatalogSource} this item belongs to. */
  sourceId: string;
  title: string;
  category: CatalogCategory;
  /** ISO 3166-2 region for coarse filtering, e.g. "CA-QC". */
  region?: string;
  bbox?: CatalogBbox;
  format: CatalogFormat;
  packaging: CatalogPackaging;
  /** Real download size from the generator's HEAD request. */
  sizeBytes?: number;
  /** The source's direct file URL — we link, we never rehost. */
  url: string;
  /** Optional world-file / aux-XML sidecar URL for plain-PDF sources (unused at M1). */
  sidecar?: string;
  thumbnailUrl?: string;
  /** Source-side revision date (ISO date); drives the "Update" flow. */
  updatedAt?: string;
  lang?: 'fr' | 'en' | 'bilingual';
}

export interface CatalogManifest {
  schemaVersion: typeof CATALOG_SCHEMA_VERSION;
  generatedAt?: string;
  sources: CatalogSource[];
  items: CatalogItem[];
}

export interface CatalogParseResult {
  /** Null when the document is unusable (see `warnings` for why). */
  manifest: CatalogManifest | null;
  warnings: string[];
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function nonEmptyString(value: unknown): value is string {
  return typeof value === 'string' && value.trim() !== '';
}

function optionalString(value: unknown): string | undefined {
  return nonEmptyString(value) ? value : undefined;
}

/** Only http(s) download URLs — anything else can't be fetched (or is unsafe). */
function isHttpUrl(value: unknown): value is string {
  return typeof value === 'string' && /^https?:\/\/\S+$/.test(value);
}

function parseBbox(value: unknown): CatalogBbox | undefined {
  if (!Array.isArray(value) || value.length !== 4) return undefined;
  const [w, s, e, n] = value;
  if (![w, s, e, n].every((x) => typeof x === 'number' && Number.isFinite(x))) return undefined;
  if ((w as number) >= (e as number) || (s as number) >= (n as number)) return undefined;
  return [w, s, e, n] as CatalogBbox;
}

function parseSource(raw: unknown): CatalogSource | null {
  if (!isRecord(raw)) return null;
  if (
    !nonEmptyString(raw.id) ||
    !nonEmptyString(raw.name) ||
    !nonEmptyString(raw.licence) ||
    !nonEmptyString(raw.attribution)
  ) {
    return null;
  }
  const homepage = optionalString(raw.homepage);
  return {
    id: raw.id,
    name: raw.name,
    licence: raw.licence,
    attribution: raw.attribution,
    ...(homepage !== undefined ? { homepage } : {}),
  };
}

function parseItem(raw: unknown, sourceIds: ReadonlySet<string>): CatalogItem | string {
  if (!isRecord(raw)) return 'item is not an object';
  const id = nonEmptyString(raw.id) ? raw.id : null;
  if (id === null) return 'item without an id';
  if (!nonEmptyString(raw.sourceId) || !sourceIds.has(raw.sourceId)) {
    return `item "${id}": unknown sourceId`;
  }
  if (!nonEmptyString(raw.title)) return `item "${id}": missing title`;
  if (!(CATALOG_CATEGORIES as readonly string[]).includes(String(raw.category))) {
    return `item "${id}": unknown category "${String(raw.category)}"`;
  }
  if (!(SUPPORTED_FORMATS as readonly string[]).includes(String(raw.format))) {
    return `item "${id}": unsupported format "${String(raw.format)}"`;
  }
  if (!isHttpUrl(raw.url)) return `item "${id}": missing or non-http url`;
  const packaging: CatalogPackaging = raw.packaging === 'zip' ? 'zip' : 'none';
  const sizeBytes =
    typeof raw.sizeBytes === 'number' && Number.isFinite(raw.sizeBytes) && raw.sizeBytes > 0
      ? Math.round(raw.sizeBytes)
      : undefined;
  const bbox = parseBbox(raw.bbox);
  const region = optionalString(raw.region);
  const sidecar = isHttpUrl(raw.sidecar) ? raw.sidecar : undefined;
  const thumbnailUrl = isHttpUrl(raw.thumbnailUrl) ? raw.thumbnailUrl : undefined;
  const updatedAt = optionalString(raw.updatedAt);
  const lang =
    raw.lang === 'fr' || raw.lang === 'en' || raw.lang === 'bilingual' ? raw.lang : undefined;
  return {
    id,
    sourceId: raw.sourceId,
    title: raw.title,
    category: raw.category as CatalogCategory,
    format: raw.format as CatalogFormat,
    packaging,
    url: raw.url,
    ...(region !== undefined ? { region } : {}),
    ...(bbox !== undefined ? { bbox } : {}),
    ...(sizeBytes !== undefined ? { sizeBytes } : {}),
    ...(sidecar !== undefined ? { sidecar } : {}),
    ...(thumbnailUrl !== undefined ? { thumbnailUrl } : {}),
    ...(updatedAt !== undefined ? { updatedAt } : {}),
    ...(lang !== undefined ? { lang } : {}),
  };
}

/**
 * Parse any JSON value into a catalog manifest. Never throws. Malformed
 * sources/items are dropped with a warning each; duplicate item ids keep the
 * first occurrence (a re-tapped Download must never see two rows for one map).
 */
export function parseCatalogManifest(raw: unknown): CatalogParseResult {
  const warnings: string[] = [];
  if (!isRecord(raw)) {
    return { manifest: null, warnings: ['manifest is not a JSON object'] };
  }
  if (raw.schemaVersion !== CATALOG_SCHEMA_VERSION) {
    return {
      manifest: null,
      warnings: [
        `unsupported manifest schemaVersion ${String(raw.schemaVersion)} (expected ${CATALOG_SCHEMA_VERSION})`,
      ],
    };
  }
  if (!Array.isArray(raw.items)) {
    return { manifest: null, warnings: ['manifest has no items array'] };
  }

  const sources: CatalogSource[] = [];
  const sourceIds = new Set<string>();
  for (const rawSource of Array.isArray(raw.sources) ? raw.sources : []) {
    const source = parseSource(rawSource);
    if (source === null) {
      warnings.push('dropped a malformed source');
      continue;
    }
    if (sourceIds.has(source.id)) {
      warnings.push(`dropped duplicate source "${source.id}"`);
      continue;
    }
    sourceIds.add(source.id);
    sources.push(source);
  }

  const items: CatalogItem[] = [];
  const itemIds = new Set<string>();
  for (const rawItem of raw.items) {
    const item = parseItem(rawItem, sourceIds);
    if (typeof item === 'string') {
      warnings.push(`dropped ${item}`);
      continue;
    }
    if (itemIds.has(item.id)) {
      warnings.push(`dropped duplicate item "${item.id}"`);
      continue;
    }
    itemIds.add(item.id);
    items.push(item);
  }

  return {
    manifest: {
      schemaVersion: CATALOG_SCHEMA_VERSION,
      ...(nonEmptyString(raw.generatedAt) ? { generatedAt: raw.generatedAt } : {}),
      sources,
      items,
    },
    warnings,
  };
}
