/**
 * Map-store catalog manifest — schema types + total parsers.
 *
 * The catalog is a set of static JSON documents generated by `scripts/catalog/`
 * and hosted on the Pages site. This module is the single source of truth for
 * their shape: the app parses fetched documents here, and the generator
 * validates its own output with the same functions before writing — so app and
 * generator cannot drift.
 *
 * Two wire shapes exist, and both parse into the same in-memory
 * {@link CatalogIndex}:
 *
 * - **v1 — one flat manifest** (`/catalog/v1/manifest.json`): every item
 *   inline. Still published for clients shipped before the world catalog, and
 *   still the shape a tiny fixture wants.
 * - **v2 — index + shards** (`/catalog/v2/index.json` + `shards/*.json`): the
 *   index carries sources, per-category totals and a small shard directory;
 *   items live in geographic shards fetched on demand. This is what keeps the
 *   client fetch small once the catalog holds tens of thousands of sheets.
 *   A v2 index MAY also carry inline `items` (small catalogs, fixtures).
 *
 * Parser contract (mirrors `parseGeoPdf` / the migration ladder): any JSON
 * value in, never throws. A fundamentally unusable document (not an object,
 * unknown `schemaVersion`, no item array) yields `null` with a reason in
 * `warnings`; malformed entries in an otherwise sound document are dropped
 * one-by-one with a warning each, so one bad row can never blank the store.
 */

/** The legacy flat-manifest schema. Breaking changes bump the /vN/ path. */
export const CATALOG_SCHEMA_VERSION = 1;

/** The sharded index schema this client prefers. */
export const CATALOG_INDEX_SCHEMA_VERSION = 2;

/** Store categories (fixed vocabulary; the generator emits only these). */
export const CATALOG_CATEGORIES = [
  'topo',
  'parks',
  'geological',
  'aerial',
  'forest',
  'hunting',
  'touristic',
  'nautical',
  'river',
] as const;

export type CatalogCategory = (typeof CATALOG_CATEGORIES)[number];

/** Chip/UI label per category. */
export const CATALOG_CATEGORY_LABELS: Record<CatalogCategory, string> = {
  topo: 'Topo',
  parks: 'Parks',
  geological: 'Geological',
  aerial: 'Aerial',
  forest: 'Forest',
  hunting: 'Hunting',
  touristic: 'Touristic',
  nautical: 'Nautical',
  river: 'River runs',
};

/** File formats this client can land in the Library. GeoTIFF is deferred (M3). */
export const SUPPORTED_FORMATS = ['geopdf', 'pdf'] as const;
export type CatalogFormat = (typeof SUPPORTED_FORMATS)[number];

/** How the downloaded bytes are wrapped. CanTopo serves its GeoPDFs zipped. */
export type CatalogPackaging = 'none' | 'zip';

/** A publisher whose products the catalog links to (attribution + licence). */
export interface CatalogSource {
  id: string;
  name: string;
  /** SPDX-ish licence label shown verbatim, e.g. "OGL-Canada-2.0". */
  licence: string;
  /** Attribution line shown in the item detail, e.g. "Natural Resources Canada". */
  attribution: string;
  homepage?: string;
}

/** WGS84 [west, south, east, north]. */
export type CatalogBbox = [number, number, number, number];

/** One downloadable product. */
export interface CatalogItem {
  /** Stable id: source + native sheet/product id, e.g. "cantopo-021l14". */
  id: string;
  /** Id of the {@link CatalogSource} this item belongs to. */
  sourceId: string;
  title: string;
  category: CatalogCategory;
  /** ISO 3166-2 region for coarse filtering, e.g. "CA-QC". */
  region?: string;
  bbox?: CatalogBbox;
  format: CatalogFormat;
  packaging: CatalogPackaging;
  /** Real download size from the generator's HEAD request. */
  sizeBytes?: number;
  /** The source's direct file URL — we link, we never rehost. */
  url: string;
  /** Optional world-file / aux-XML sidecar URL for plain-PDF sources (unused at M1). */
  sidecar?: string;
  thumbnailUrl?: string;
  /** Source-side revision date (ISO date); drives the "Update" flow. */
  updatedAt?: string;
  lang?: 'fr' | 'en' | 'bilingual';
}

export interface CatalogManifest {
  schemaVersion: typeof CATALOG_SCHEMA_VERSION;
  generatedAt?: string;
  sources: CatalogSource[];
  items: CatalogItem[];
}

export interface CatalogParseResult {
  /** Null when the document is unusable (see `warnings` for why). */
  manifest: CatalogManifest | null;
  warnings: string[];
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function nonEmptyString(value: unknown): value is string {
  return typeof value === 'string' && value.trim() !== '';
}

function optionalString(value: unknown): string | undefined {
  return nonEmptyString(value) ? value : undefined;
}

/** Only http(s) download URLs — anything else can't be fetched (or is unsafe). */
function isHttpUrl(value: unknown): value is string {
  return typeof value === 'string' && /^https?:\/\/\S+$/.test(value);
}

function parseBbox(value: unknown): CatalogBbox | undefined {
  if (!Array.isArray(value) || value.length !== 4) return undefined;
  const [w, s, e, n] = value;
  if (![w, s, e, n].every((x) => typeof x === 'number' && Number.isFinite(x))) return undefined;
  if ((w as number) >= (e as number) || (s as number) >= (n as number)) return undefined;
  return [w, s, e, n] as CatalogBbox;
}

function parseSource(raw: unknown): CatalogSource | null {
  if (!isRecord(raw)) return null;
  if (
    !nonEmptyString(raw.id) ||
    !nonEmptyString(raw.name) ||
    !nonEmptyString(raw.licence) ||
    !nonEmptyString(raw.attribution)
  ) {
    return null;
  }
  const homepage = optionalString(raw.homepage);
  return {
    id: raw.id,
    name: raw.name,
    licence: raw.licence,
    attribution: raw.attribution,
    ...(homepage !== undefined ? { homepage } : {}),
  };
}

function parseItem(raw: unknown, sourceIds: ReadonlySet<string>): CatalogItem | string {
  if (!isRecord(raw)) return 'item is not an object';
  const id = nonEmptyString(raw.id) ? raw.id : null;
  if (id === null) return 'item without an id';
  if (!nonEmptyString(raw.sourceId) || !sourceIds.has(raw.sourceId)) {
    return `item "${id}": unknown sourceId`;
  }
  if (!nonEmptyString(raw.title)) return `item "${id}": missing title`;
  if (!(CATALOG_CATEGORIES as readonly string[]).includes(String(raw.category))) {
    return `item "${id}": unknown category "${String(raw.category)}"`;
  }
  if (!(SUPPORTED_FORMATS as readonly string[]).includes(String(raw.format))) {
    return `item "${id}": unsupported format "${String(raw.format)}"`;
  }
  if (!isHttpUrl(raw.url)) return `item "${id}": missing or non-http url`;
  const packaging: CatalogPackaging = raw.packaging === 'zip' ? 'zip' : 'none';
  const sizeBytes =
    typeof raw.sizeBytes === 'number' && Number.isFinite(raw.sizeBytes) && raw.sizeBytes > 0
      ? Math.round(raw.sizeBytes)
      : undefined;
  const bbox = parseBbox(raw.bbox);
  const region = optionalString(raw.region);
  const sidecar = isHttpUrl(raw.sidecar) ? raw.sidecar : undefined;
  const thumbnailUrl = isHttpUrl(raw.thumbnailUrl) ? raw.thumbnailUrl : undefined;
  const updatedAt = optionalString(raw.updatedAt);
  const lang =
    raw.lang === 'fr' || raw.lang === 'en' || raw.lang === 'bilingual' ? raw.lang : undefined;
  return {
    id,
    sourceId: raw.sourceId,
    title: raw.title,
    category: raw.category as CatalogCategory,
    format: raw.format as CatalogFormat,
    packaging,
    url: raw.url,
    ...(region !== undefined ? { region } : {}),
    ...(bbox !== undefined ? { bbox } : {}),
    ...(sizeBytes !== undefined ? { sizeBytes } : {}),
    ...(sidecar !== undefined ? { sidecar } : {}),
    ...(thumbnailUrl !== undefined ? { thumbnailUrl } : {}),
    ...(updatedAt !== undefined ? { updatedAt } : {}),
    ...(lang !== undefined ? { lang } : {}),
  };
}

/**
 * Parse any JSON value into a catalog manifest. Never throws. Malformed
 * sources/items are dropped with a warning each; duplicate item ids keep the
 * first occurrence (a re-tapped Download must never see two rows for one map).
 */
export function parseCatalogManifest(raw: unknown): CatalogParseResult {
  const warnings: string[] = [];
  if (!isRecord(raw)) {
    return { manifest: null, warnings: ['manifest is not a JSON object'] };
  }
  if (raw.schemaVersion !== CATALOG_SCHEMA_VERSION) {
    return {
      manifest: null,
      warnings: [
        `unsupported manifest schemaVersion ${String(raw.schemaVersion)} (expected ${CATALOG_SCHEMA_VERSION})`,
      ],
    };
  }
  if (!Array.isArray(raw.items)) {
    return { manifest: null, warnings: ['manifest has no items array'] };
  }

  const sources: CatalogSource[] = [];
  const sourceIds = new Set<string>();
  for (const rawSource of Array.isArray(raw.sources) ? raw.sources : []) {
    const source = parseSource(rawSource);
    if (source === null) {
      warnings.push('dropped a malformed source');
      continue;
    }
    if (sourceIds.has(source.id)) {
      warnings.push(`dropped duplicate source "${source.id}"`);
      continue;
    }
    sourceIds.add(source.id);
    sources.push(source);
  }

  const items: CatalogItem[] = [];
  const itemIds = new Set<string>();
  for (const rawItem of raw.items) {
    const item = parseItem(rawItem, sourceIds);
    if (typeof item === 'string') {
      warnings.push(`dropped ${item}`);
      continue;
    }
    if (itemIds.has(item.id)) {
      warnings.push(`dropped duplicate item "${item.id}"`);
      continue;
    }
    itemIds.add(item.id);
    items.push(item);
  }

  return {
    manifest: {
      schemaVersion: CATALOG_SCHEMA_VERSION,
      ...(nonEmptyString(raw.generatedAt) ? { generatedAt: raw.generatedAt } : {}),
      sources,
      items,
    },
    warnings,
  };
}

/* ------------------------------------------------------------------ v2 --- */

/**
 * One shard file in the index's directory. `path` is relative to the index
 * URL, so the whole catalog can move host (or be served from a loopback
 * fixture server in e2e) without regenerating shard bodies.
 */
export interface CatalogShardRef {
  /** Stable shard id, e.g. "topo-n45w075" — also the on-device cache key. */
  id: string;
  category: CatalogCategory;
  /** Relative path from the index document, e.g. "shards/topo-n45w075.json". */
  path: string;
  itemCount: number;
  /** Union of the shard's item bboxes — what nearest-shard ranking measures. */
  bbox?: CatalogBbox;
  /** Serialized size, so the client can budget what it prefetches. */
  byteSize?: number;
}

/** The small document the client fetches first (and caches for offline). */
export interface CatalogIndex {
  schemaVersion: typeof CATALOG_INDEX_SCHEMA_VERSION;
  generatedAt?: string;
  sources: CatalogSource[];
  /** Shard directory; empty for a small/inline catalog. */
  shards: CatalogShardRef[];
  /** Items carried inline (v1 manifests, tiny catalogs, fixtures). */
  items: CatalogItem[];
  /**
   * Total items per category across shards *and* inline items — the landing
   * grid shows real counts without fetching a single shard.
   */
  categoryCounts: Partial<Record<CatalogCategory, number>>;
}

export interface CatalogIndexParseResult {
  index: CatalogIndex | null;
  warnings: string[];
}

/** Items of one shard, already filtered to the sources the index declares. */
export interface CatalogShardParseResult {
  items: CatalogItem[];
  warnings: string[];
}

/** A shard id must be safe to use as a flat cache filename. */
function isShardId(value: unknown): value is string {
  return typeof value === 'string' && /^[a-z0-9][a-z0-9._-]{0,63}$/.test(value);
}

/** Shard paths are relative and must not climb out of the catalog directory. */
function isShardPath(value: unknown): value is string {
  return (
    typeof value === 'string' &&
    value !== '' &&
    !value.startsWith('/') &&
    !value.includes('..') &&
    !/^[a-z][a-z0-9+.-]*:/i.test(value)
  );
}

function parseShardRef(raw: unknown): CatalogShardRef | string {
  if (!isRecord(raw)) return 'shard ref is not an object';
  if (!isShardId(raw.id)) return `shard ref with an unusable id "${String(raw.id)}"`;
  if (!(CATALOG_CATEGORIES as readonly string[]).includes(String(raw.category))) {
    return `shard "${raw.id}": unknown category "${String(raw.category)}"`;
  }
  if (!isShardPath(raw.path)) return `shard "${raw.id}": unusable path`;
  const itemCount =
    typeof raw.itemCount === 'number' && Number.isFinite(raw.itemCount) && raw.itemCount > 0
      ? Math.round(raw.itemCount)
      : null;
  if (itemCount === null) return `shard "${raw.id}": missing itemCount`;
  const bbox = parseBbox(raw.bbox);
  const byteSize =
    typeof raw.byteSize === 'number' && Number.isFinite(raw.byteSize) && raw.byteSize > 0
      ? Math.round(raw.byteSize)
      : undefined;
  return {
    id: raw.id,
    category: raw.category as CatalogCategory,
    path: raw.path,
    itemCount,
    ...(bbox !== undefined ? { bbox } : {}),
    ...(byteSize !== undefined ? { byteSize } : {}),
  };
}

/** Per-category totals, ignoring unknown keys and non-positive numbers. */
function parseCategoryCounts(raw: unknown): Partial<Record<CatalogCategory, number>> {
  const counts: Partial<Record<CatalogCategory, number>> = {};
  if (!isRecord(raw)) return counts;
  for (const category of CATALOG_CATEGORIES) {
    const value = raw[category];
    if (typeof value === 'number' && Number.isFinite(value) && value > 0) {
      counts[category] = Math.round(value);
    }
  }
  return counts;
}

/** Category totals implied by a list of inline items (the v1 fallback). */
function countsFromItems(items: readonly CatalogItem[]): Partial<Record<CatalogCategory, number>> {
  const counts: Partial<Record<CatalogCategory, number>> = {};
  for (const item of items) counts[item.category] = (counts[item.category] ?? 0) + 1;
  return counts;
}

/**
 * Parse any JSON value into a {@link CatalogIndex}. Accepts **both** wire
 * shapes: a v2 index (shard directory, optional inline items) and a v1 flat
 * manifest (adapted to an index with every item inline and no shards). Never
 * throws; returns `index: null` only for a document neither shape can use.
 *
 * Accepting v1 here is what lets a cached document written by an older build —
 * or a two-file e2e fixture — keep working after the client moves to /v2/.
 */
export function parseCatalogIndex(raw: unknown): CatalogIndexParseResult {
  if (isRecord(raw) && raw.schemaVersion === CATALOG_SCHEMA_VERSION) {
    const { manifest, warnings } = parseCatalogManifest(raw);
    if (manifest === null) return { index: null, warnings };
    return {
      index: {
        schemaVersion: CATALOG_INDEX_SCHEMA_VERSION,
        ...(manifest.generatedAt !== undefined ? { generatedAt: manifest.generatedAt } : {}),
        sources: manifest.sources,
        shards: [],
        items: manifest.items,
        categoryCounts: countsFromItems(manifest.items),
      },
      warnings,
    };
  }

  const warnings: string[] = [];
  if (!isRecord(raw)) return { index: null, warnings: ['catalog index is not a JSON object'] };
  if (raw.schemaVersion !== CATALOG_INDEX_SCHEMA_VERSION) {
    return {
      index: null,
      warnings: [
        `unsupported catalog schemaVersion ${String(raw.schemaVersion)} (expected ${CATALOG_INDEX_SCHEMA_VERSION} or ${CATALOG_SCHEMA_VERSION})`,
      ],
    };
  }

  const sources: CatalogSource[] = [];
  const sourceIds = new Set<string>();
  for (const rawSource of Array.isArray(raw.sources) ? raw.sources : []) {
    const source = parseSource(rawSource);
    if (source === null) {
      warnings.push('dropped a malformed source');
      continue;
    }
    if (sourceIds.has(source.id)) {
      warnings.push(`dropped duplicate source "${source.id}"`);
      continue;
    }
    sourceIds.add(source.id);
    sources.push(source);
  }

  const shards: CatalogShardRef[] = [];
  const shardIds = new Set<string>();
  for (const rawShard of Array.isArray(raw.shards) ? raw.shards : []) {
    const shard = parseShardRef(rawShard);
    if (typeof shard === 'string') {
      warnings.push(`dropped ${shard}`);
      continue;
    }
    if (shardIds.has(shard.id)) {
      warnings.push(`dropped duplicate shard "${shard.id}"`);
      continue;
    }
    shardIds.add(shard.id);
    shards.push(shard);
  }

  const { items, warnings: itemWarnings } = parseCatalogShard(raw.items, sourceIds);
  warnings.push(...itemWarnings);

  if (shards.length === 0 && items.length === 0) {
    return { index: null, warnings: [...warnings, 'catalog index has neither shards nor items'] };
  }

  const declared = parseCategoryCounts(raw.categoryCounts);
  // A shardless index states its own totals badly at most once; fall back to
  // what the inline items actually contain so the grid never shows "0 maps".
  const categoryCounts = Object.keys(declared).length > 0 ? declared : countsFromItems(items);

  return {
    index: {
      schemaVersion: CATALOG_INDEX_SCHEMA_VERSION,
      ...(nonEmptyString(raw.generatedAt) ? { generatedAt: raw.generatedAt } : {}),
      sources,
      shards,
      items,
      categoryCounts,
    },
    warnings,
  };
}

/**
 * Parse a shard body's items. Accepts either the shard document
 * (`{ items: [...] }`) or a bare array, and drops rows whose `sourceId` the
 * index never declared — a shard can't smuggle in an unattributed source.
 */
export function parseCatalogShard(
  raw: unknown,
  sourceIds: ReadonlySet<string>,
): CatalogShardParseResult {
  const list = Array.isArray(raw)
    ? raw
    : isRecord(raw) && Array.isArray(raw.items)
      ? raw.items
      : [];
  const warnings: string[] = [];
  if (!Array.isArray(raw) && !(isRecord(raw) && Array.isArray(raw.items))) {
    if (raw !== undefined) warnings.push('shard has no items array');
    return { items: [], warnings };
  }
  const items: CatalogItem[] = [];
  const itemIds = new Set<string>();
  for (const rawItem of list) {
    const item = parseItem(rawItem, sourceIds);
    if (typeof item === 'string') {
      warnings.push(`dropped ${item}`);
      continue;
    }
    if (itemIds.has(item.id)) {
      warnings.push(`dropped duplicate item "${item.id}"`);
      continue;
    }
    itemIds.add(item.id);
    items.push(item);
  }
  return { items, warnings };
}
