import StaticServer, { ERROR_LOG_FILE } from '@dr.pogodin/react-native-static-server';
import { Directory, File, Paths } from 'expo-file-system';
import { uuid } from 'expo-modules-core';

import { PROBE_TIMEOUT_MS } from '@core/storage/loopbackLiveness';
import { refCounted, type RefCountedLease } from '@core/storage/refCounted';
import {
  SERVED_DOCUMENT_PREFIXES,
  lighttpdAccessConfig,
  servedBase,
} from '@core/storage/servedPaths';
import {
  describeServerStartFailure,
  fileUriOfPath,
  logTail,
} from '@core/storage/serverStartFailure';

import { documentDirUri } from './storage';
import { keepAlive } from '@data/keepAlive';

/**
 * The app's ONE loopback HTTP server (#269).
 *
 * `@dr.pogodin/react-native-static-server` permits a single active server per
 * app — its native `stop()` takes no id — so every subsystem that needs a
 * local `http://` origin shares this instance through a ref-counted lease:
 *
 * - the PDF rasterizer holds a lease for the app's lifetime: its WebView page
 *   and the imported PDFs are served from here, same-origin, so pdf.js can
 *   range-fetch a 200 MB GeoPDF instead of the file crossing the bridge as
 *   base64 (the OOM / timeout in #218, #264, #265);
 * - the offline-map downloader holds one per download: MapLibre's native
 *   downloader accepts only http(s) style URLs.
 *
 * Root = the document directory, bound to 127.0.0.1 on a free port. Only the
 * folders in {@link SERVED_DOCUMENT_PREFIXES} are reachable — lighttpd's
 * mod_access denies the rest, so the user's index, trails and photos are not
 * one guessed URL away from any process on the device — and only under this
 * JS session's random secret: a lease's `value` is
 * `http://127.0.0.1:<port>/<secret>`, and a URL without the secret is denied,
 * because on Android any app may connect to loopback. Loopback cleartext is
 * allowed by the withLocalhostCleartext plugin (Android) and
 * NSAllowsLocalNetworking (iOS).
 *
 * ## Start failures (#290)
 *
 * On one Android 11 phone lighttpd exited with status -1 twice in a row
 * (#276, #277) and the library's error carries nothing else. So a failed
 * start is retried once on a FRESH instance (the library forbids restarting
 * a crashed one), and if that fails too the thrown error carries the tail of
 * lighttpd's own error log — the only place the real reason is written.
 *
 * The log only exists because the server is built with `errorLog: true`
 * (#327). Without it the library hands lighttpd an empty log path and a
 * `server.errorlog-use-syslog` line, so every start failure went to logcat and
 * 37 field reports from that phone said "(no lighttpd error log)". With it,
 * the native launcher redirects lighttpd's stderr to {@link ERROR_LOG_FILE}
 * before it parses the config, so config, module and bind errors all land
 * there. The file is cleared before each start, so its tail is that start's.
 *
 * ## Death under a live lease (iOS resume)
 *
 * iOS reclaims a suspended app's listening sockets; lighttpd keeps running
 * with a dead listener and the library still says ACTIVE (see
 * `@core/storage/loopbackLiveness`). {@link probeLocalServer} tells whether a
 * connection is accepted; {@link restartLocalServer} replaces the server in
 * place — on the SAME port when it can be had again, so every URL already
 * handed out (the rasterizer page, an offline download's style) stays valid,
 * and on a new port only if that bind fails.
 */

/** Starts attempted before giving up: the first, plus one on a fresh instance. */
export const START_ATTEMPTS = 2;

/**
 * How long a restart waits for the old server to stop. The native stop holds
 * a semaphore the next start waits on forever, so a stop that does not finish
 * must not be followed by a start.
 */
export const STOP_TIMEOUT_MS = 3_000;

// The native server wants a plain filesystem path; expo-file-system gives file:// URIs.
function fsPath(uri: string): string {
  return uri.replace(/^file:\/\//, '');
}

// The single instance. Created lazily and kept while it works: the lib's
// start() is idempotent while ACTIVE and permitted again from INACTIVE, so one
// object serves every lease. A crashed instance is dropped (see startServer).
let server: StaticServer | null = null;
// The origin of the last successful start: a restart asks for its port again.
let lastOrigin: string | null = null;

// This JS session's URL secret (see isServerSecret in @core/storage/servedPaths).
// One per session, kept across restarts so the URLs already handed out stay
// valid. Generated by the native CSPRNG (java.util.UUID / Foundation UUID); if
// that is unavailable the start fails and callers fall back as for any failed
// start — never a server without a secret.
let secret: string | null = null;

function sessionSecret(): string {
  secret ??= uuid.v4();
  return secret;
}

function sharedServer(port: number): StaticServer {
  if (server === null) {
    const fileDir = fsPath(documentDirUri());
    server = new StaticServer({
      fileDir,
      port,
      hostname: '127.0.0.1',
      // Write lighttpd's errors to ERROR_LOG_FILE (no debug categories, so only
      // real errors and the one "server started" line). Off, they go to syslog
      // and a failed start cannot say why (#327).
      errorLog: true,
      extraConfig: lighttpdAccessConfig(SERVED_DOCUMENT_PREFIXES, sessionSecret(), fileDir),
    });
  }
  return server;
}

/** The library gives a plain filesystem path; expo-file-system takes a uri. */
function errorLogFile(): File {
  return new File(fileUriOfPath(ERROR_LOG_FILE));
}

/** The tail of lighttpd's error log, or null when it cannot be read. */
async function readErrorLogTail(): Promise<string | null> {
  try {
    const file = errorLogFile();
    if (!file.exists) return null;
    return logTail(await keepAlive(file, file.text()));
  } catch {
    return null;
  }
}

/** Start each attempt with an empty log, so a failure's tail is its own. */
function clearErrorLog(): void {
  try {
    const file = errorLogFile();
    if (file.exists) file.delete();
  } catch {
    // Best effort: a stale tail is still better than none.
  }
}

/** `preferredPort` is tried first; a retry always takes any free port. */
async function startServer(preferredPort = 0): Promise<string> {
  let lastError: unknown;
  for (let attempt = 1; attempt <= START_ATTEMPTS; attempt++) {
    clearErrorLog();
    try {
      const origin = await sharedServer(attempt === 1 ? preferredPort : 0).start();
      lastOrigin = origin;
      return servedBase(origin, sessionSecret());
    } catch (err) {
      lastError = err;
      // Never reuse an instance that crashed: the library's own contract, and
      // the second failure on #276/#277 was exactly such a reuse.
      server = null;
    }
  }
  throw new Error(describeServerStartFailure(lastError, await readErrorLogTail(), START_ATTEMPTS));
}

/**
 * Replace a server whose listener died: stop it (bounded), then start a FRESH
 * instance on the same port — lighttpd sets SO_REUSEADDR, and the library
 * reuses an explicit port as given.
 */
async function restartServer(): Promise<string> {
  const dead = server;
  const port = Number(/:(\d+)$/.exec(lastOrigin ?? '')?.[1] ?? 0);
  server = null;
  lastOrigin = null;
  if (dead !== null) {
    let timer: ReturnType<typeof setTimeout> | undefined;
    const stopped = await Promise.race([
      dead.stop().then(
        () => true,
        // A stop that fails leaves the instance CRASHED, its thread gone.
        () => true,
      ),
      new Promise<boolean>((resolve) => {
        timer = setTimeout(() => resolve(false), STOP_TIMEOUT_MS);
      }),
    ]);
    clearTimeout(timer);
    if (!stopped) {
      throw new Error(`Loopback server did not stop within ${STOP_TIMEOUT_MS} ms; not restarting`);
    }
  }
  return startServer(port);
}

const pool = refCounted<string>(
  startServer,
  () =>
    server === null
      ? Promise.resolve()
      : server.stop().then(
          () => undefined,
          () => undefined,
        ),
  restartServer,
);

/**
 * A held reference to the running server; `value` is the base every served URL
 * is built on (`http://127.0.0.1:<port>/<secret>`, see `servedFileUrl`).
 */
export type LocalServerLease = RefCountedLease<string>;

/**
 * Start the server (or join the running one) and return a lease on it. The
 * server stops once every lease is released. Rejects if it cannot start —
 * callers decide what to do without it (the rasterizer falls back to the
 * bridge for small files; a download simply fails).
 */
export function acquireLocalServer(): Promise<LocalServerLease> {
  return pool.acquire();
}

/**
 * Replace the server under its live leases after `staleOrigin` stopped
 * accepting connections. Resolves to the new origin — the same one when its
 * port could be bound again — which every lease's `value` now reads. A second
 * caller reporting the same dead origin joins the first restart. Rejects when
 * the server cannot be brought back (callers fall back as for a failed start).
 */
export function restartLocalServer(staleOrigin: string): Promise<string> {
  return pool.restart(staleOrigin);
}

/**
 * Does the server at `origin` accept a connection? Any HTTP answer counts —
 * `<base>/` itself is outside the served allowlist, so a live server answers 403
 * without touching a file. A refused connection, a network error or no answer
 * within `timeoutMs` means it is dead.
 */
export async function probeLocalServer(
  origin: string,
  timeoutMs: number = PROBE_TIMEOUT_MS,
): Promise<boolean> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    await fetch(`${origin.replace(/\/+$/, '')}/`, {
      method: 'HEAD',
      cache: 'no-store',
      signal: controller.signal,
    });
    return true;
  } catch {
    return false;
  } finally {
    clearTimeout(timer);
  }
}

/** Outstanding leases — for diagnostics and tests. */
export function localServerLeases(): number {
  return pool.leases;
}

/**
 * Write a text file into the document directory at `documentPath`
 * (creating parent folders), overwriting any previous version, and return
 * its `file://` uri. The rasterizer page is written this way on every mount.
 */
/**
 * Copy a file (any `file://` uri) to a document-relative path under the
 * served root, creating folders as needed, and return the copy's `file://`
 * uri. The rasterizer page reads a native tile this way to key its white.
 */
export async function copyToServed(sourceUri: string, documentPath: string): Promise<string> {
  const slash = documentPath.lastIndexOf('/');
  const dir =
    slash === -1
      ? new Directory(Paths.document)
      : new Directory(Paths.document, documentPath.slice(0, slash));
  if (!dir.exists) dir.create({ intermediates: true });
  const file = new File(dir, documentPath.slice(slash + 1));
  if (file.exists) file.delete();
  await new File(sourceUri).copy(file);
  return file.uri;
}

export function writeServedText(documentPath: string, text: string): string {
  const slash = documentPath.lastIndexOf('/');
  const dir =
    slash === -1
      ? new Directory(Paths.document)
      : new Directory(Paths.document, documentPath.slice(0, slash));
  if (!dir.exists) dir.create({ intermediates: true });
  const file = new File(dir, documentPath.slice(slash + 1));
  if (file.exists) file.delete();
  file.create();
  file.write(text);
  return file.uri;
}
